"""Base damage of an attack whose damage MOVES, evaluated at decision time.

`GameProc.h:AttackDamage` uses `attack.damage + state.attackDamageChange`; the second term is
written by the attack's own effects while it resolves, so the printed number is only a floor.
Measured over 38,295 decisions on 63 decks: **31.2% of offered attack options have dynamic
damage** (37.1% of the decisions that offer an attack at all), and with `glossary="none"` the
prompt carries no damage number whatsoever -- the model has only the `a1234` token, which cannot
encode a value that changes every turn.

The formulas come from the engine, not from card text: `lm/damage_table.json` is generated by
tools/gen_damage_table.py from `DebugDamageFormula`. This evaluates them against the visible
board plus the decoded hidden state (lm/hidden.py).

Three outcomes, kept distinct because they mean different things to a player:

    exact       the quantity is a count of something visible (bench, hand size, damage counters,
                prizes taken, attached energy) or something we decode -- the number IS the damage
    expected    a coin decides it. The value is E[damage]; the realised one is not knowable.
    None        not evaluable -- the count depends on a sub-select the player has not made yet
                (`Effected`), on a condition this evaluator does not implement, or on a hidden
                zone. NOTHING is rendered in that case; a confident wrong number is worse than
                the status quo, which is what the retreat-cost bug cost us.

Coverage is deliberately partial and measured rather than assumed: tools/verify_base_damage.py
compares every prediction against the base damage the engine actually used (recorded by the
build_engine_mirror patch) and reports both accuracy and the share left unrendered.
"""

import json
import os

_TABLE = None

# EffectType values that write state.attackDamageChange. Names from Types.h.
_FLAT = 73                  # AttackDamageChange              value, gated by a preceding cond
_TARGET_COUNT = 74          # AttackDamageChangeTargetCount   value x |targetList|
_ENERGY_COUNT = 76          # AttackDamageChangeEnergyCount   value x energy on targetList
_TAKEN_PRIZE = 86           # AttackDamageChangeTakenPrize    value x prizes taken
_DAMAGE_COUNTER = 88        # AttackDamageChangeDamageCounter value x (damage/10) on targetList
_COIN_UNTIL_TAIL = 83       # AttackDamageChangeCoinUntilTail value x heads (E[heads] = 1)
_DMG_PRE_TURN = 94          # AttackDamageChangeTakeAttackDamagePreTurn
_BREAK_IF_COIN_TAIL = 164   # BreakIfCoinTail  -- everything after it happens only on heads

# EVERY EffectType that writes state.attackDamageChange (Types.h 71-95) plus the coin gates.
# An unhandled member of this set must make the whole prediction FAIL rather than fall through:
# ignoring it silently returns the printed damage as if it were exact, which is how a578
# "Double Kick" (printed 0, engine 40) was predicted as 0 on the first run of
# tools/verify_base_damage.py.
_WRITES_DAMAGE = set(range(71, 96)) | {163, 164}
_HANDLED = {_FLAT, _TARGET_COUNT, _ENERGY_COUNT, _TAKEN_PRIZE, _DAMAGE_COUNTER,
            _COIN_UNTIL_TAIL, _DMG_PRE_TURN, _BREAK_IF_COIN_TAIL}

# AreaType
_A_HAND, _A_ACTIVE, _A_BENCH, _A_SELF = 2, 4, 5, 15
# TargetPlayer bitmask
_P_ME, _P_ENEMY = 1, 2
# TargetType conditions this evaluator implements. Anything else -> not evaluable.
_T_STAGE2, _T_CARD_ID, _T_DAMAGE_COUNTER = 11, 20, 90


def table():
    global _TABLE
    if _TABLE is None:
        p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "damage_table.json")
        try:
            _TABLE = {int(k): v for k, v in json.load(open(p)).items()}
        except Exception:
            _TABLE = {}
    return _TABLE


def _mons(obs, pi, areas):
    """In-play Pokemon of player `pi` in the requested areas, as (serial, json) pairs."""
    out = []
    try:
        pl = obs["current"]["players"][pi]
    except (KeyError, IndexError, TypeError):
        return out
    if _A_ACTIVE in areas or _A_SELF in areas:
        for m in (pl.get("active") or []):
            if m:
                out.append(m)
    if _A_BENCH in areas:
        for m in (pl.get("bench") or []):
            if m:
                out.append(m)
    return out


def _cond_ok(m, conds):
    """-> True / False / None (None = a condition this evaluator does not implement)."""
    from lm import vocab
    for c in conds:
        t = c.get("targetType")
        master = vocab._CARDS.get(m.get("id"))
        if t == _T_STAGE2:
            if not (master and master.stage2):
                return False
        elif t == _T_CARD_ID:
            if m.get("id") != c.get("val"):
                return False
        elif t == _T_DAMAGE_COUNTER:
            if (m.get("maxHp", 0) - m.get("hp", 0)) <= 0:
                return False
        else:
            return None
    return True


def _target_mons(obs, e, me_pi, attacker_serial):
    """Pokemon selected by one Effect's target spec, or None if it cannot be resolved."""
    areas = e.get("areas") or []
    if not areas or any(a not in (_A_ACTIVE, _A_BENCH, _A_SELF) for a in areas):
        return None                     # Hand / Deck / Effected / Energy -- not a Pokemon count
    tp = e.get("targetPlayer") or 0
    got = []
    for pi in (0, 1):
        mine = (pi == me_pi)
        if not ((tp & _P_ME) if mine else (tp & _P_ENEMY)):
            continue
        for m in _mons(obs, pi, areas):
            if _A_SELF in areas and areas == [_A_SELF] and m.get("serial") != attacker_serial:
                continue
            ok = _cond_ok(m, e.get("conditions") or [])
            if ok is None:
                return None
            if ok:
                got.append(m)
    return got


def _hand_count(obs, e, me_pi):
    """`areas == [Hand]`: a count of cards in hand. Only countable with no conditions -- the
    opponent's hand is a number, not a list, and our own would need the condition semantics."""
    if (e.get("areas") or []) != [_A_HAND] or (e.get("conditions") or []):
        return None
    tp = e.get("targetPlayer") or 0
    n = 0
    for pi in (0, 1):
        mine = (pi == me_pi)
        if not ((tp & _P_ME) if mine else (tp & _P_ENEMY)):
            continue
        try:
            pl = obs["current"]["players"][pi]
        except (KeyError, IndexError, TypeError):
            return None
        n += pl.get("handCount") if pl.get("handCount") is not None else len(pl.get("hand") or [])
    return n


def base_damage(obs, dec, attacker_serial, attack_id, me_pi):
    """-> (damage, kind) with kind in {"exact", "expected"}, or (None, None) if not evaluable.

    `damage` is the base the engine would use -- printed plus the dynamic part. It still has to
    go through lm/hidden.attack_facts (weakness, target effects, immunity) to become the number
    that actually lands.
    """
    entry = table().get(attack_id)
    if entry is None:
        from lm import vocab
        at = vocab._ATTACKS.get(attack_id)
        return (at.damage, "exact") if at is not None else (None, None)

    dmg = entry["printed"]
    kind = "exact"
    effects = entry["effects"]
    i = 0
    coin_gate = 1.0
    while i < len(effects):
        e = effects[i]
        i += 1
        t = e.get("effectType")
        if t == _BREAK_IF_COIN_TAIL:
            coin_gate *= 0.5            # everything after happens only on heads
            kind = "expected"
            continue
        if e.get("isCondition"):
            # A gate we cannot evaluate: the effects it guards may or may not run.
            return (None, None)
        if t in _WRITES_DAMAGE and t not in _HANDLED:
            return (None, None)         # fail closed -- see _WRITES_DAMAGE
        if t == _FLAT:
            dmg += e["v0"] * coin_gate
        elif t == _TARGET_COUNT:
            mons = _target_mons(obs, e, me_pi, attacker_serial)
            if mons is None:
                n = _hand_count(obs, e, me_pi)
                if n is None:
                    return (None, None)
            else:
                n = len(mons)
            dmg += e["v0"] * n * coin_gate
        elif t == _ENERGY_COUNT:
            mons = _target_mons(obs, e, me_pi, attacker_serial)
            if mons is None:
                return (None, None)
            dmg += e["v0"] * sum(len(m.get("energies") or []) for m in mons) * coin_gate
        elif t == _DAMAGE_COUNTER:
            mons = _target_mons(obs, e, me_pi, attacker_serial)
            if mons is None:
                return (None, None)
            dmg += e["v0"] * sum((m.get("maxHp", 0) - m.get("hp", 0)) // 10
                                 for m in mons) * coin_gate
        elif t == _TAKEN_PRIZE:
            tp = e.get("targetPlayer") or 0
            n = 0
            for pi in (0, 1):
                mine = (pi == me_pi)
                if not ((tp & _P_ME) if mine else (tp & _P_ENEMY)):
                    continue
                try:
                    n += 6 - len(obs["current"]["players"][pi].get("prize") or [])
                except (KeyError, IndexError, TypeError):
                    return (None, None)
            dmg += e["v0"] * max(0, n) * coin_gate
        elif t == _COIN_UNTIL_TAIL:
            dmg += e["v0"] * 1.0 * coin_gate    # E[heads before the first tail] = 1
            kind = "expected"
        elif t == _DMG_PRE_TURN:
            c = (dec or {}).get("cards", {}).get(attacker_serial)
            if c is None:
                return (None, None)
            dmg += c["takeAttackDamagePreTurn"] * coin_gate
        # every other effect type does not touch attackDamageChange (asserted by _WRITES_DAMAGE)
    return (int(round(dmg)), kind)
