"""Deck agent: archaludon (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"arch_mixin": true, "archetype": "ramp", "card_roles": {"1097": "engine", "1121": "engine", "1122": "engine", "1147": "tech", "1152": "engine", "1159": "tech", "1182": "tech", "1185": "engine", "1197": "tech", "1227": "engine", "1244": "engine", "169": "line", "190": "win", "57": "tech", "666": "engine", "8": "fuel"}, "disrupt_cards": [1197], "engine": "v2", "heal_cards": [1147], "l2": "config", "line": {"big": [224, 253, 965], "discard_fuel": [], "focus": [190, 169, 666], "need": {"169": 3, "190": 3, "666": 1}, "stadiums": [1244]}, "search_items": [1185], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("archaludon")
PROFILE = {'arch_mixin': True, 'archetype': 'ramp', 'card_roles': {'1097': 'engine', '1121': 'engine', '1122': 'engine', '1147': 'tech', '1152': 'engine', '1159': 'tech', '1182': 'tech', '1185': 'engine', '1197': 'tech', '1227': 'engine', '1244': 'engine', '169': 'line', '190': 'win', '57': 'tech', '666': 'engine', '8': 'fuel'}, 'disrupt_cards': [1197], 'engine': 'v2', 'heal_cards': [1147], 'l2': 'config', 'line': {'big': [224, 253, 965], 'discard_fuel': [], 'focus': [190, 169, 666], 'need': {'169': 3, '190': 3, '666': 1}, 'stadiums': [1244]}, 'search_items': [1185], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
