"""Deck agent: black_kyurem (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_dawn_note": "Do NOT add draw_supporters=[Dawn 1231] to the decks that run Dawn. Tested on all 10 of them at matched 150 games/opponent: the 5 where Dawn actually started firing (black_kyurem 1.35/g, mega_heracross 1.22, hydreigon 0.95, marnie_grimmsnarl 0.66, zangoose 0.60) averaged +0.84pt -- and the other 5, where Dawn went 0.00 -> 0.00 and the pilot did not change AT ALL, averaged +0.72pt while swinging -3.8 to +4.2. That unchanged cohort IS the noise floor of the experiment, and the effect is inside it. Dawn only paid off on alakazam because it was paired with draw_threshold=30, which is only justified where the damage IS the hand size (Powerful Hand = 20 x hand). Here the default draw_threshold=5 gate blocks it anyway.", "archetype": "spread", "card_roles": {"1086": "engine", "1097": "engine", "1119": "engine", "1121": "engine", "1122": "engine", "1125": "engine", "1152": "tech", "1182": "tech", "1205": "engine", "1210": "engine", "1227": "engine", "1231": "engine", "140": "engine", "179": "win", "3": "fuel", "305": "engine"}, "engine": "v2", "l2": "black_kyurem", "search_items": [1210, 1231], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("black_kyurem")
PROFILE = {'_dawn_note': 'Do NOT add draw_supporters=[Dawn 1231] to the decks that run Dawn. Tested on all 10 of them at matched 150 games/opponent: the 5 where Dawn actually started firing (black_kyurem 1.35/g, mega_heracross 1.22, hydreigon 0.95, marnie_grimmsnarl 0.66, zangoose 0.60) averaged +0.84pt -- and the other 5, where Dawn went 0.00 -> 0.00 and the pilot did not change AT ALL, averaged +0.72pt while swinging -3.8 to +4.2. That unchanged cohort IS the noise floor of the experiment, and the effect is inside it. Dawn only paid off on alakazam because it was paired with draw_threshold=30, which is only justified where the damage IS the hand size (Powerful Hand = 20 x hand). Here the default draw_threshold=5 gate blocks it anyway.', 'archetype': 'spread', 'card_roles': {'1086': 'engine', '1097': 'engine', '1119': 'engine', '1121': 'engine', '1122': 'engine', '1125': 'engine', '1152': 'tech', '1182': 'tech', '1205': 'engine', '1210': 'engine', '1227': 'engine', '1231': 'engine', '140': 'engine', '179': 'win', '3': 'fuel', '305': 'engine'}, 'engine': 'v2', 'l2': 'black_kyurem', 'search_items': [1210, 1231], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
