"""Deck agent: ceruledge (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"1097": "engine", "11": "tech", "1121": "engine", "1128": "engine", "1142": "engine", "1152": "engine", "1182": "tech", "1185": "engine", "1192": "engine", "1256": "tech", "140": "engine", "2": "fuel", "204": "line", "319": "line", "320": "win", "6": "fuel", "675": "engine", "676": "engine", "796": "line"}, "engine": "v2", "l2": "config", "line": {"big": [183, 446, 980], "discard_fuel": [], "focus": [320, 676, 140], "need": {"140": 3, "320": 1, "676": 1}, "stadiums": [1256]}, "search_items": [1185], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("ceruledge")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'1097': 'engine', '11': 'tech', '1121': 'engine', '1128': 'engine', '1142': 'engine', '1152': 'engine', '1182': 'tech', '1185': 'engine', '1192': 'engine', '1256': 'tech', '140': 'engine', '2': 'fuel', '204': 'line', '319': 'line', '320': 'win', '6': 'fuel', '675': 'engine', '676': 'engine', '796': 'line'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [183, 446, 980], 'discard_fuel': [], 'focus': [320, 676, 140], 'need': {'140': 3, '320': 1, '676': 1}, 'stadiums': [1256]}, 'search_items': [1185], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
