"""Deck agent: chandelure (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"arch_mixin": true, "archetype": "control", "card_roles": {"1079": "engine", "1081": "tech", "1086": "engine", "1097": "engine", "1119": "tech", "1120": "tech", "1123": "tech", "1152": "engine", "1166": "tech", "1182": "tech", "1186": "tech", "1197": "tech", "1225": "engine", "1227": "engine", "1231": "engine", "1247": "engine", "164": "engine", "2": "fuel", "343": "tech", "494": "line", "5": "fuel", "97": "line", "98": "win"}, "engine": "v2", "l2": "config", "line": {"big": [123, 216, 699], "discard_fuel": [], "focus": [98, 494, 164], "need": {"164": 1, "494": 1, "98": 1}, "stadiums": [1247]}, "search_items": [1231], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("chandelure")
PROFILE = {'arch_mixin': True, 'archetype': 'control', 'card_roles': {'1079': 'engine', '1081': 'tech', '1086': 'engine', '1097': 'engine', '1119': 'tech', '1120': 'tech', '1123': 'tech', '1152': 'engine', '1166': 'tech', '1182': 'tech', '1186': 'tech', '1197': 'tech', '1225': 'engine', '1227': 'engine', '1231': 'engine', '1247': 'engine', '164': 'engine', '2': 'fuel', '343': 'tech', '494': 'line', '5': 'fuel', '97': 'line', '98': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [123, 216, 699], 'discard_fuel': [], 'focus': [98, 494, 164], 'need': {'164': 1, '494': 1, '98': 1}, 'stadiums': [1247]}, 'search_items': [1231], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
