"""Deck agent: comfey_yveltal (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "MILL/control: Comfey Flower Shower decks the opponent out behind Neutralization Zone (blanks attacks on non-Rule-Box Pokemon). Yveltal is NOT the win condition -- mis-tagging it `win` misled both the focus config and an energy edit. Real gap: the engine never plays disruption (Xerosic 929 offers/0 plays, Crushing Hammer 596/0, Acerola 118/0).", "arch_mixin": true, "archetype": "control", "card_roles": {"1086": "engine", "1097": "engine", "1120": "engine", "1122": "engine", "1152": "engine", "1161": "tech", "1182": "engine", "1194": "engine", "1197": "engine", "1227": "engine", "1228": "tech", "1247": "engine", "16": "fuel", "164": "win", "19": "fuel", "343": "tech", "5": "fuel", "689": "tech"}, "energy_denial_cards": [1120], "engine": "v2", "l2": "config", "line": {"big": [216, 477], "discard_fuel": [], "focus": [164, 343], "need": {"164": 1, "343": 2}, "stadiums": [1247]}, "residual_cards": [1228], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("comfey_yveltal")
PROFILE = {'_line_note': 'MILL/control: Comfey Flower Shower decks the opponent out behind Neutralization Zone (blanks attacks on non-Rule-Box Pokemon). Yveltal is NOT the win condition -- mis-tagging it `win` misled both the focus config and an energy edit. Real gap: the engine never plays disruption (Xerosic 929 offers/0 plays, Crushing Hammer 596/0, Acerola 118/0).', 'arch_mixin': True, 'archetype': 'control', 'card_roles': {'1086': 'engine', '1097': 'engine', '1120': 'engine', '1122': 'engine', '1152': 'engine', '1161': 'tech', '1182': 'engine', '1194': 'engine', '1197': 'engine', '1227': 'engine', '1228': 'tech', '1247': 'engine', '16': 'fuel', '164': 'win', '19': 'fuel', '343': 'tech', '5': 'fuel', '689': 'tech'}, 'energy_denial_cards': [1120], 'engine': 'v2', 'l2': 'config', 'line': {'big': [216, 477], 'discard_fuel': [], 'focus': [164, 343], 'need': {'164': 1, '343': 2}, 'stadiums': [1247]}, 'residual_cards': [1228], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
