"""Deck agent: crustle (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"1": "fuel", "1086": "engine", "1087": "tech", "11": "fuel", "1122": "engine", "1123": "engine", "1147": "tech", "1159": "tech", "1182": "tech", "1197": "engine", "1225": "engine", "1227": "engine", "1264": "tech", "14": "fuel", "18": "fuel", "343": "tech", "344": "line", "345": "engine", "756": "win"}, "disrupt_cards": [1197], "engine": "v2", "hand_reset_cards": [1087], "heal_cards": [1147], "l2": "config", "line": {"big": [477, 479, 1092], "discard_fuel": [], "focus": [756, 345, 343], "need": {"343": 2, "345": 3, "756": 3}, "stadiums": [1264]}, "live": {"best_score": 584.2, "last_submitted": "2026-07-15", "submissions": 5}, "promote_ready": true, "status": "submitted", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("crustle")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'1': 'fuel', '1086': 'engine', '1087': 'tech', '11': 'fuel', '1122': 'engine', '1123': 'engine', '1147': 'tech', '1159': 'tech', '1182': 'tech', '1197': 'engine', '1225': 'engine', '1227': 'engine', '1264': 'tech', '14': 'fuel', '18': 'fuel', '343': 'tech', '344': 'line', '345': 'engine', '756': 'win'}, 'disrupt_cards': [1197], 'engine': 'v2', 'hand_reset_cards': [1087], 'heal_cards': [1147], 'l2': 'config', 'line': {'big': [477, 479, 1092], 'discard_fuel': [], 'focus': [756, 345, 343], 'need': {'343': 2, '345': 3, '756': 3}, 'stadiums': [1264]}, 'live': {'best_score': 584.2, 'last_submitted': '2026-07-15', 'submissions': 5}, 'promote_ready': True, 'status': 'submitted', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
