"""Deck agent: crustle_geco (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_note": "scouted from leaderboard #12 gecogeco 1095.6 (2026-07-19)", "archetype": "control", "bench_target": 4, "card_roles": {"1": "fuel", "1086": "engine", "1087": "tech", "11": "engine", "1121": "engine", "1122": "engine", "1123": "tech", "1147": "tech", "1159": "tech", "117": "tech", "1187": "engine", "1197": "tech", "1225": "engine", "1227": "engine", "1264": "tech", "14": "engine", "18": "engine", "20": "engine", "344": "line", "345": "win", "756": "win"}, "disrupt_cards": [1197], "draw_supporters": [1187], "draw_threshold": 5, "engine": "v2", "hand_reset_cards": [1087], "heal_cards": [1147], "l2": "config", "line": {"bench_target": 4, "big": [1092, 479, 148], "discard_fuel": [], "focus": [756, 345, 117], "need": {"117": 3, "345": 3, "756": 3}, "stadiums": [1264]}, "main_attackers": [756, 345, 117], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("crustle_geco")
PROFILE = {'_note': 'scouted from leaderboard #12 gecogeco 1095.6 (2026-07-19)', 'archetype': 'control', 'bench_target': 4, 'card_roles': {'1': 'fuel', '1086': 'engine', '1087': 'tech', '11': 'engine', '1121': 'engine', '1122': 'engine', '1123': 'tech', '1147': 'tech', '1159': 'tech', '117': 'tech', '1187': 'engine', '1197': 'tech', '1225': 'engine', '1227': 'engine', '1264': 'tech', '14': 'engine', '18': 'engine', '20': 'engine', '344': 'line', '345': 'win', '756': 'win'}, 'disrupt_cards': [1197], 'draw_supporters': [1187], 'draw_threshold': 5, 'engine': 'v2', 'hand_reset_cards': [1087], 'heal_cards': [1147], 'l2': 'config', 'line': {'bench_target': 4, 'big': [1092, 479, 148], 'discard_fuel': [], 'focus': [756, 345, 117], 'need': {'117': 3, '345': 3, '756': 3}, 'stadiums': [1264]}, 'main_attackers': [756, 345, 117], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
