"""Deck agent: crustle_stall (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"arch_mixin": true, "archetype": "control", "card_roles": {"1": "fuel", "1086": "engine", "112": "engine", "1129": "tech", "1147": "engine", "1152": "engine", "1159": "tech", "117": "win", "1177": "tech", "1182": "tech", "1197": "tech", "1198": "engine", "1210": "engine", "1227": "engine", "1264": "tech", "16": "fuel", "18": "fuel", "344": "line", "345": "win", "414": "tech", "6": "fuel", "7": "fuel"}, "deck_recover_cards": [1129], "disrupt_cards": [1197], "engine": "v2", "heal_cards": [1147], "l2": "config", "line": {"big": [148, 479], "discard_fuel": [], "focus": [117, 345], "need": {"117": 3, "345": 3}, "stadiums": [1264], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "live": {"best_score": 664.7, "last_submitted": "2026-07-12", "submissions": 10}, "search_items": [1210], "status": "submitted", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("crustle_stall")
PROFILE = {'arch_mixin': True, 'archetype': 'control', 'card_roles': {'1': 'fuel', '1086': 'engine', '112': 'engine', '1129': 'tech', '1147': 'engine', '1152': 'engine', '1159': 'tech', '117': 'win', '1177': 'tech', '1182': 'tech', '1197': 'tech', '1198': 'engine', '1210': 'engine', '1227': 'engine', '1264': 'tech', '16': 'fuel', '18': 'fuel', '344': 'line', '345': 'win', '414': 'tech', '6': 'fuel', '7': 'fuel'}, 'deck_recover_cards': [1129], 'disrupt_cards': [1197], 'engine': 'v2', 'heal_cards': [1147], 'l2': 'config', 'line': {'big': [148, 479], 'discard_fuel': [], 'focus': [117, 345], 'need': {'117': 3, '345': 3}, 'stadiums': [1264], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'live': {'best_score': 664.7, 'last_submitted': '2026-07-12', 'submissions': 10}, 'search_items': [1210], 'status': 'submitted', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
