"""Deck agent: cubchoo_control (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"arch_mixin": true, "archetype": "control", "card_roles": {"1081": "engine", "1086": "engine", "1091": "tech", "1097": "engine", "1102": "engine", "1119": "engine", "1120": "engine", "1137": "tech", "1152": "engine", "1166": "engine", "1182": "engine", "1186": "tech", "1197": "engine", "1227": "engine", "1247": "engine", "1266": "tech", "174": "tech", "3": "fuel", "506": "win", "65": "line", "66": "engine"}, "energy_denial_cards": [1120], "engine": "v2", "l2": "cubchoo_control", "residual_cards": [1137], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("cubchoo_control")
PROFILE = {'arch_mixin': True, 'archetype': 'control', 'card_roles': {'1081': 'engine', '1086': 'engine', '1091': 'tech', '1097': 'engine', '1102': 'engine', '1119': 'engine', '1120': 'engine', '1137': 'tech', '1152': 'engine', '1166': 'engine', '1182': 'engine', '1186': 'tech', '1197': 'engine', '1227': 'engine', '1247': 'engine', '1266': 'tech', '174': 'tech', '3': 'fuel', '506': 'win', '65': 'line', '66': 'engine'}, 'energy_denial_cards': [1120], 'engine': 'v2', 'l2': 'cubchoo_control', 'residual_cards': [1137], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
