"""Deck agent: cynthia_garchomp (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"10": "engine", "1079": "engine", "1086": "engine", "1097": "tech", "1122": "engine", "1123": "tech", "1141": "tech", "1142": "engine", "1152": "engine", "1173": "tech", "1182": "tech", "1213": "tech", "1225": "engine", "1227": "engine", "20": "fuel", "341": "line", "342": "engine", "379": "line", "380": "line", "381": "win", "387": "tech", "6": "fuel"}, "damage_boost_cards": {"1141": 30}, "engine": "v2", "l2": "cynthia_garchomp", "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("cynthia_garchomp")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'10': 'engine', '1079': 'engine', '1086': 'engine', '1097': 'tech', '1122': 'engine', '1123': 'tech', '1141': 'tech', '1142': 'engine', '1152': 'engine', '1173': 'tech', '1182': 'tech', '1213': 'tech', '1225': 'engine', '1227': 'engine', '20': 'fuel', '341': 'line', '342': 'engine', '379': 'line', '380': 'line', '381': 'win', '387': 'tech', '6': 'fuel'}, 'damage_boost_cards': {'1141': 30}, 'engine': 'v2', 'l2': 'cynthia_garchomp', 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
