"""Deck agent: doublade (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "combo", "card_roles": {"1065": "line", "1066": "win", "1067": "win", "1079": "engine", "1086": "engine", "1097": "engine", "1121": "engine", "1122": "engine", "1152": "engine", "1182": "tech", "1198": "engine", "1225": "engine", "1227": "engine", "13": "fuel", "547": "engine", "7": "fuel", "8": "fuel"}, "engine": "v2", "l2": "doublade", "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("doublade")
PROFILE = {'archetype': 'combo', 'card_roles': {'1065': 'line', '1066': 'win', '1067': 'win', '1079': 'engine', '1086': 'engine', '1097': 'engine', '1121': 'engine', '1122': 'engine', '1152': 'engine', '1182': 'tech', '1198': 'engine', '1225': 'engine', '1227': 'engine', '13': 'fuel', '547': 'engine', '7': 'fuel', '8': 'fuel'}, 'engine': 'v2', 'l2': 'doublade', 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
