"""Deck agent: dragapult_blaziken (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1071": "engine", "1079": "engine", "1080": "tech", "1086": "engine", "1097": "tech", "112": "engine", "1121": "engine", "1152": "engine", "1182": "engine", "119": "line", "1198": "engine", "120": "line", "121": "win", "1227": "engine", "1231": "engine", "1250": "engine", "1256": "tech", "140": "engine", "2": "fuel", "235": "tech", "272": "win", "31": "tech", "326": "win", "343": "tech", "410": "line", "411": "line", "5": "fuel", "7": "fuel"}, "draw_supporters": [1080], "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [154, 371, 453], "discard_fuel": [], "focus": [272, 121, 326], "need": {"121": 2, "272": 2, "326": 2}, "stadiums": [1250, 1256], "support_energy": {"112": 1}, "support_etype": {"112": 7}, "support_gate": "lenient"}, "search_items": [1231], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("dragapult_blaziken")
PROFILE = {'archetype': 'spread', 'card_roles': {'1071': 'engine', '1079': 'engine', '1080': 'tech', '1086': 'engine', '1097': 'tech', '112': 'engine', '1121': 'engine', '1152': 'engine', '1182': 'engine', '119': 'line', '1198': 'engine', '120': 'line', '121': 'win', '1227': 'engine', '1231': 'engine', '1250': 'engine', '1256': 'tech', '140': 'engine', '2': 'fuel', '235': 'tech', '272': 'win', '31': 'tech', '326': 'win', '343': 'tech', '410': 'line', '411': 'line', '5': 'fuel', '7': 'fuel'}, 'draw_supporters': [1080], 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [154, 371, 453], 'discard_fuel': [], 'focus': [272, 121, 326], 'need': {'121': 2, '272': 2, '326': 2}, 'stadiums': [1250, 1256], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}, 'support_gate': 'lenient'}, 'search_items': [1231], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
