"""Deck agent: dragapult (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_migration_note": "NOT on ConfigL2: its `need` is a COUNT, and Phantom Dive (154) costs [2,5] = {R}+{P}, a two-TYPE cost. `need:{121:2}` is satisfied by any 2 energy, so the deck always had a payable Jet Headbutt (cost [0]) and led with it -- Phantom Dive 48.5% (legacy) -> 24.1% (config), i.e. the deck stopped being a spread deck. archetype='spread' -> SpreadPolicy restores it: Phantom Dive back in the lead (36.5%) and winrate 44.5 -> 51.2 at 150 games/opp. GAP: the line config has no vocabulary for typed needs.", "archetype": "spread", "card_roles": {"1071": "engine", "1079": "engine", "1080": "tech", "1086": "engine", "1097": "tech", "112": "engine", "1120": "tech", "1121": "engine", "1152": "engine", "1182": "engine", "119": "line", "1198": "engine", "120": "line", "121": "win", "1227": "engine", "1240": "tech", "1260": "tech", "140": "engine", "2": "fuel", "235": "tech", "305": "line", "5": "fuel", "66": "engine", "7": "fuel"}, "draw_supporters": [1080], "energy_accel": [1240], "engine": "v2", "line": {"big": [152, 154, 183], "discard_fuel": [], "focus": [121, 120, 140], "need": {"120": 2, "121": 2, "140": 3}, "stadiums": [1260], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "residual_cards": [1120, 1240], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("dragapult")
PROFILE = {'_migration_note': "NOT on ConfigL2: its `need` is a COUNT, and Phantom Dive (154) costs [2,5] = {R}+{P}, a two-TYPE cost. `need:{121:2}` is satisfied by any 2 energy, so the deck always had a payable Jet Headbutt (cost [0]) and led with it -- Phantom Dive 48.5% (legacy) -> 24.1% (config), i.e. the deck stopped being a spread deck. archetype='spread' -> SpreadPolicy restores it: Phantom Dive back in the lead (36.5%) and winrate 44.5 -> 51.2 at 150 games/opp. GAP: the line config has no vocabulary for typed needs.", 'archetype': 'spread', 'card_roles': {'1071': 'engine', '1079': 'engine', '1080': 'tech', '1086': 'engine', '1097': 'tech', '112': 'engine', '1120': 'tech', '1121': 'engine', '1152': 'engine', '1182': 'engine', '119': 'line', '1198': 'engine', '120': 'line', '121': 'win', '1227': 'engine', '1240': 'tech', '1260': 'tech', '140': 'engine', '2': 'fuel', '235': 'tech', '305': 'line', '5': 'fuel', '66': 'engine', '7': 'fuel'}, 'draw_supporters': [1080], 'energy_accel': [1240], 'engine': 'v2', 'line': {'big': [152, 154, 183], 'discard_fuel': [], 'focus': [121, 120, 140], 'need': {'120': 2, '121': 2, '140': 3}, 'stadiums': [1260], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'residual_cards': [1120, 1240], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
