"""Deck agent: dragapult_dusknoir (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1071": "engine", "1080": "engine", "1086": "engine", "1097": "tech", "112": "engine", "1120": "tech", "1121": "engine", "1152": "engine", "1161": "tech", "1182": "engine", "119": "line", "1198": "engine", "120": "line", "121": "win", "1227": "engine", "1231": "engine", "1256": "tech", "131": "line", "132": "line", "133": "win", "140": "engine", "2": "fuel", "235": "tech", "5": "fuel", "7": "fuel"}, "draw_supporters": [1080], "energy_denial_cards": [1120], "engine": "v2", "l2": "config", "line": {"big": [152, 154, 172], "discard_fuel": [], "focus": [121, 133, 120], "need": {"120": 2, "121": 2, "133": 3}, "stadiums": [1256], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "search_items": [1231], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("dragapult_dusknoir")
PROFILE = {'archetype': 'spread', 'card_roles': {'1071': 'engine', '1080': 'engine', '1086': 'engine', '1097': 'tech', '112': 'engine', '1120': 'tech', '1121': 'engine', '1152': 'engine', '1161': 'tech', '1182': 'engine', '119': 'line', '1198': 'engine', '120': 'line', '121': 'win', '1227': 'engine', '1231': 'engine', '1256': 'tech', '131': 'line', '132': 'line', '133': 'win', '140': 'engine', '2': 'fuel', '235': 'tech', '5': 'fuel', '7': 'fuel'}, 'draw_supporters': [1080], 'energy_denial_cards': [1120], 'engine': 'v2', 'l2': 'config', 'line': {'big': [152, 154, 172], 'discard_fuel': [], 'focus': [121, 133, 120], 'need': {'120': 2, '121': 2, '133': 3}, 'stadiums': [1256], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'search_items': [1231], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
