"""Deck agent: ethan_hooh (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1088": "tech", "1097": "engine", "1118": "engine", "1121": "engine", "1122": "engine", "1152": "engine", "1182": "tech", "1198": "engine", "1205": "engine", "1215": "engine", "1227": "engine", "1256": "tech", "140": "engine", "184": "engine", "2": "fuel", "338": "tech", "355": "line", "356": "win", "357": "win"}, "engine": "v2", "l2": "ethan_hooh", "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("ethan_hooh")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1088': 'tech', '1097': 'engine', '1118': 'engine', '1121': 'engine', '1122': 'engine', '1152': 'engine', '1182': 'tech', '1198': 'engine', '1205': 'engine', '1215': 'engine', '1227': 'engine', '1256': 'tech', '140': 'engine', '184': 'engine', '2': 'fuel', '338': 'tech', '355': 'line', '356': 'win', '357': 'win'}, 'engine': 'v2', 'l2': 'ethan_hooh', 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
