"""Deck agent: flareon (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory", "archetype": "toolbox", "card_roles": {"1": "fuel", "108": "tech", "1086": "engine", "1097": "tech", "1119": "tech", "1121": "engine", "1123": "tech", "1127": "engine", "1152": "engine", "1165": "engine", "1174": "tech", "1182": "tech", "1198": "engine", "1205": "engine", "1211": "tech", "1227": "engine", "1250": "tech", "140": "engine", "172": "line", "173": "engine", "174": "engine", "184": "engine", "2": "fuel", "236": "tech", "239": "win", "249": "line", "272": "tech", "3": "fuel", "317": "line", "4": "fuel", "5": "fuel", "848": "line", "849": "win"}, "damage_boost_cards": {"1211": 40}, "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [324, 329, 371], "discard_fuel": [], "focus": [272, 239, 236], "need": {"236": 2, "239": 3, "272": 2}, "stadiums": [1250]}, "residual_cards": [1211], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("flareon")
PROFILE = {'_line_note': 'win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory', 'archetype': 'toolbox', 'card_roles': {'1': 'fuel', '108': 'tech', '1086': 'engine', '1097': 'tech', '1119': 'tech', '1121': 'engine', '1123': 'tech', '1127': 'engine', '1152': 'engine', '1165': 'engine', '1174': 'tech', '1182': 'tech', '1198': 'engine', '1205': 'engine', '1211': 'tech', '1227': 'engine', '1250': 'tech', '140': 'engine', '172': 'line', '173': 'engine', '174': 'engine', '184': 'engine', '2': 'fuel', '236': 'tech', '239': 'win', '249': 'line', '272': 'tech', '3': 'fuel', '317': 'line', '4': 'fuel', '5': 'fuel', '848': 'line', '849': 'win'}, 'damage_boost_cards': {'1211': 40}, 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [324, 329, 371], 'discard_fuel': [], 'focus': [272, 239, 236], 'need': {'236': 2, '239': 3, '272': 2}, 'stadiums': [1250]}, 'residual_cards': [1211], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
