"""Deck agent: garchomp_lucario (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"1079": "engine", "1086": "engine", "1088": "tech", "1097": "tech", "1121": "engine", "1122": "engine", "1129": "tech", "1139": "tech", "1141": "tech", "1142": "engine", "1152": "engine", "117": "tech", "1173": "tech", "1174": "tech", "1182": "tech", "1203": "engine", "1227": "engine", "20": "fuel", "341": "line", "342": "engine", "379": "line", "380": "line", "381": "win", "387": "tech", "6": "fuel", "677": "line", "678": "win"}, "damage_boost_cards": {"1141": 30}, "deck_recover_cards": [1129], "draw_supporters": [1203], "engine": "v2", "l2": "config", "line": {"big": [148, 532, 983], "discard_fuel": [], "focus": [381, 678, 117], "need": {"117": 3, "381": 2, "678": 2}, "stadiums": []}, "main_attackers": [678, 381], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("garchomp_lucario")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'1079': 'engine', '1086': 'engine', '1088': 'tech', '1097': 'tech', '1121': 'engine', '1122': 'engine', '1129': 'tech', '1139': 'tech', '1141': 'tech', '1142': 'engine', '1152': 'engine', '117': 'tech', '1173': 'tech', '1174': 'tech', '1182': 'tech', '1203': 'engine', '1227': 'engine', '20': 'fuel', '341': 'line', '342': 'engine', '379': 'line', '380': 'line', '381': 'win', '387': 'tech', '6': 'fuel', '677': 'line', '678': 'win'}, 'damage_boost_cards': {'1141': 30}, 'deck_recover_cards': [1129], 'draw_supporters': [1203], 'engine': 'v2', 'l2': 'config', 'line': {'big': [148, 532, 983], 'discard_fuel': [], 'focus': [381, 678, 117], 'need': {'117': 3, '381': 2, '678': 2}, 'stadiums': []}, 'main_attackers': [678, 381], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
