"""Deck agent: hop_zacian (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "win Zacian ex last in focus at need=1; big forced self-damaging Dynamic Press", "archetype": "aggro", "card_roles": {"1092": "engine", "1097": "tech", "11": "fuel", "1115": "engine", "1121": "engine", "1122": "engine", "1123": "tech", "1152": "engine", "1171": "engine", "1182": "tech", "1213": "engine", "1219": "engine", "1227": "engine", "1255": "engine", "140": "engine", "299": "win", "304": "engine", "309": "tech", "310": "tech", "311": "tech", "626": "tech", "8": "fuel", "878": "line", "879": "tech"}, "engine": "v2", "l2": "config", "line": {"big": [413, 433, 412], "discard_fuel": [], "focus": [299, 311], "need": {"299": 4, "311": 1}, "stadiums": [1255]}, "main_attackers": [299], "search_items": [1092, 1115], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("hop_zacian")
PROFILE = {'_line_note': 'win Zacian ex last in focus at need=1; big forced self-damaging Dynamic Press', 'archetype': 'aggro', 'card_roles': {'1092': 'engine', '1097': 'tech', '11': 'fuel', '1115': 'engine', '1121': 'engine', '1122': 'engine', '1123': 'tech', '1152': 'engine', '1171': 'engine', '1182': 'tech', '1213': 'engine', '1219': 'engine', '1227': 'engine', '1255': 'engine', '140': 'engine', '299': 'win', '304': 'engine', '309': 'tech', '310': 'tech', '311': 'tech', '626': 'tech', '8': 'fuel', '878': 'line', '879': 'tech'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [413, 433, 412], 'discard_fuel': [], 'focus': [299, 311], 'need': {'299': 4, '311': 1}, 'stadiums': [1255]}, 'main_attackers': [299], 'search_items': [1092, 1115], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
