"""Deck agent: hydreigon (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"10": "engine", "1079": "engine", "1086": "engine", "112": "tech", "1121": "engine", "1139": "tech", "1225": "engine", "1227": "engine", "1231": "engine", "1260": "tech", "140": "tech", "141": "tech", "227": "line", "228": "line", "229": "win", "5": "fuel", "7": "fuel", "8": "fuel", "827": "line", "828": "win", "833": "line", "834": "engine"}, "engine": "v2", "l2": "config", "line": {"big": [184, 313, 1192], "discard_fuel": [], "focus": [229, 141, 828], "need": {"141": 2, "229": 2, "828": 1}, "stadiums": [1260], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "residual_cards": [1231], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("hydreigon")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'10': 'engine', '1079': 'engine', '1086': 'engine', '112': 'tech', '1121': 'engine', '1139': 'tech', '1225': 'engine', '1227': 'engine', '1231': 'engine', '1260': 'tech', '140': 'tech', '141': 'tech', '227': 'line', '228': 'line', '229': 'win', '5': 'fuel', '7': 'fuel', '8': 'fuel', '827': 'line', '828': 'win', '833': 'line', '834': 'engine'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [184, 313, 1192], 'discard_fuel': [], 'focus': [229, 141, 828], 'need': {'141': 2, '229': 2, '828': 1}, 'stadiums': [1260], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'residual_cards': [1231], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
