"""Deck agent: hydrapple (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "combo", "card_roles": {"1": "fuel", "1071": "engine", "1080": "engine", "1094": "engine", "1097": "tech", "1121": "engine", "1152": "engine", "1182": "tech", "1184": "tech", "1201": "engine", "1227": "engine", "1231": "engine", "1261": "engine", "140": "engine", "150": "win", "172": "tech", "173": "tech", "655": "engine", "708": "line", "709": "line", "710": "engine", "917": "line", "918": "line", "92": "line", "920": "tech", "93": "line", "96": "win"}, "draw_supporters": [1080], "engine": "v2", "l2": "hydrapple", "main_attackers": [96, 150], "search_items": [1231], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("hydrapple")
PROFILE = {'archetype': 'combo', 'card_roles': {'1': 'fuel', '1071': 'engine', '1080': 'engine', '1094': 'engine', '1097': 'tech', '1121': 'engine', '1152': 'engine', '1182': 'tech', '1184': 'tech', '1201': 'engine', '1227': 'engine', '1231': 'engine', '1261': 'engine', '140': 'engine', '150': 'win', '172': 'tech', '173': 'tech', '655': 'engine', '708': 'line', '709': 'line', '710': 'engine', '917': 'line', '918': 'line', '92': 'line', '920': 'tech', '93': 'line', '96': 'win'}, 'draw_supporters': [1080], 'engine': 'v2', 'l2': 'hydrapple', 'main_attackers': [96, 150], 'search_items': [1231], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
