"""Deck agent: iono_bellibolt (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "Bellowing Thunder costs LIGHTNING+FIGHTING and Electric Streamer attaches only Basic {L} to IONO'S Pokemon -- so the engine cannot fuel the primary attacker at all (wrong type AND wrong target). Raging Bolt depends on the 1/turn manual attach with 3 Basic {F} in 60. A bespoke L2 was written and REFUTED; see archetype-policy-never-ran / the iono entry in the weak-deck memo.", "archetype": "ramp", "card_roles": {"1086": "engine", "1088": "tech", "1097": "tech", "1116": "tech", "1118": "engine", "1119": "tech", "1121": "engine", "1152": "engine", "1182": "tech", "1227": "engine", "1233": "engine", "1254": "engine", "235": "tech", "265": "tech", "268": "line", "269": "win", "270": "line", "271": "engine", "343": "tech", "4": "fuel", "6": "fuel", "63": "win"}, "engine": "v2", "l2": "config", "line": {"big": [72, 363, 368], "discard_fuel": [], "focus": [63, 269, 265], "need": {"265": 2, "269": 4, "63": 2}, "stadiums": [1254]}, "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("iono_bellibolt")
PROFILE = {'_line_note': "Bellowing Thunder costs LIGHTNING+FIGHTING and Electric Streamer attaches only Basic {L} to IONO'S Pokemon -- so the engine cannot fuel the primary attacker at all (wrong type AND wrong target). Raging Bolt depends on the 1/turn manual attach with 3 Basic {F} in 60. A bespoke L2 was written and REFUTED; see archetype-policy-never-ran / the iono entry in the weak-deck memo.", 'archetype': 'ramp', 'card_roles': {'1086': 'engine', '1088': 'tech', '1097': 'tech', '1116': 'tech', '1118': 'engine', '1119': 'tech', '1121': 'engine', '1152': 'engine', '1182': 'tech', '1227': 'engine', '1233': 'engine', '1254': 'engine', '235': 'tech', '265': 'tech', '268': 'line', '269': 'win', '270': 'line', '271': 'engine', '343': 'tech', '4': 'fuel', '6': 'fuel', '63': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [72, 363, 368], 'discard_fuel': [], 'focus': [63, 269, 265], 'need': {'265': 2, '269': 4, '63': 2}, 'stadiums': [1254]}, 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
