"""Deck agent: lillies_clefairy (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "toolbox", "card_roles": {"1071": "engine", "108": "win", "1088": "tech", "1102": "engine", "1121": "engine", "1146": "engine", "1172": "tech", "1182": "tech", "1188": "engine", "1198": "engine", "1205": "engine", "1250": "engine", "140": "tech", "184": "engine", "19": "fuel", "2": "fuel", "209": "tech", "272": "win", "3": "fuel", "5": "fuel", "6": "fuel", "756": "win", "791": "tech", "979": "tech"}, "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [136, 371, 1092], "discard_fuel": [5], "focus": [272, 756, 108], "need": {"108": 3, "272": 2, "756": 3}, "stadiums": [1250]}, "search_items": [1188], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("lillies_clefairy")
PROFILE = {'archetype': 'toolbox', 'card_roles': {'1071': 'engine', '108': 'win', '1088': 'tech', '1102': 'engine', '1121': 'engine', '1146': 'engine', '1172': 'tech', '1182': 'tech', '1188': 'engine', '1198': 'engine', '1205': 'engine', '1250': 'engine', '140': 'tech', '184': 'engine', '19': 'fuel', '2': 'fuel', '209': 'tech', '272': 'win', '3': 'fuel', '5': 'fuel', '6': 'fuel', '756': 'win', '791': 'tech', '979': 'tech'}, 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [136, 371, 1092], 'discard_fuel': [5], 'focus': [272, 756, 108], 'need': {'108': 3, '272': 2, '756': 3}, 'stadiums': [1250]}, 'search_items': [1188], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
