"""Deck agent: mamoswine (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "combo", "card_roles": {"1079": "engine", "1086": "engine", "109": "line", "1097": "tech", "1121": "engine", "1123": "tech", "1152": "engine", "1182": "tech", "1188": "engine", "1198": "engine", "12": "fuel", "1225": "engine", "1227": "engine", "1264": "tech", "140": "tech", "167": "tech", "2": "fuel", "20": "fuel", "281": "line", "282": "line", "283": "win", "326": "engine", "410": "line", "411": "line", "5": "fuel", "6": "fuel", "741": "line", "742": "line", "743": "engine"}, "engine": "v2", "l2": "mamoswine", "main_attackers": [283], "roles": {"283": {"payoff": true, "role": "attacker", "tier": "primary"}}, "search_items": [1188], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mamoswine")
PROFILE = {'archetype': 'combo', 'card_roles': {'1079': 'engine', '1086': 'engine', '109': 'line', '1097': 'tech', '1121': 'engine', '1123': 'tech', '1152': 'engine', '1182': 'tech', '1188': 'engine', '1198': 'engine', '12': 'fuel', '1225': 'engine', '1227': 'engine', '1264': 'tech', '140': 'tech', '167': 'tech', '2': 'fuel', '20': 'fuel', '281': 'line', '282': 'line', '283': 'win', '326': 'engine', '410': 'line', '411': 'line', '5': 'fuel', '6': 'fuel', '741': 'line', '742': 'line', '743': 'engine'}, 'engine': 'v2', 'l2': 'mamoswine', 'main_attackers': [283], 'roles': {'283': {'payoff': True, 'role': 'attacker', 'tier': 'primary'}}, 'search_items': [1188], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
