"""Deck agent: manectric (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1071": "tech", "1086": "engine", "1093": "tech", "1097": "tech", "1119": "tech", "1121": "engine", "1123": "tech", "1152": "engine", "1174": "tech", "1182": "tech", "1203": "tech", "1213": "tech", "1219": "engine", "1227": "engine", "1239": "engine", "1264": "tech", "140": "tech", "235": "tech", "272": "tech", "343": "tech", "377": "tech", "4": "fuel", "5": "fuel", "511": "line", "512": "engine", "736": "line", "737": "win", "868": "win", "946": "tech"}, "draw_supporters": [1203, 1239], "engine": "v2", "l2": "manectric", "save_cards": [1093], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("manectric")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1071': 'tech', '1086': 'engine', '1093': 'tech', '1097': 'tech', '1119': 'tech', '1121': 'engine', '1123': 'tech', '1152': 'engine', '1174': 'tech', '1182': 'tech', '1203': 'tech', '1213': 'tech', '1219': 'engine', '1227': 'engine', '1239': 'engine', '1264': 'tech', '140': 'tech', '235': 'tech', '272': 'tech', '343': 'tech', '377': 'tech', '4': 'fuel', '5': 'fuel', '511': 'line', '512': 'engine', '736': 'line', '737': 'win', '868': 'win', '946': 'tech'}, 'draw_supporters': [1203, 1239], 'engine': 'v2', 'l2': 'manectric', 'save_cards': [1093], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
