"""Deck agent: marnie_grimmsnarl (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"103": "line", "104": "engine", "1079": "engine", "1080": "tech", "1086": "engine", "1097": "tech", "112": "engine", "1122": "engine", "1152": "engine", "1174": "tech", "1182": "tech", "1219": "engine", "122": "engine", "1227": "engine", "1259": "engine", "235": "tech", "646": "line", "647": "line", "648": "win", "689": "tech", "7": "fuel"}, "draw_supporters": [1080], "engine": "v2", "l2": "marnie_grimmsnarl", "live": {"best_score": 575.2, "last_submitted": "2026-07-11", "submissions": 4}, "status": "submitted", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("marnie_grimmsnarl")
PROFILE = {'archetype': 'spread', 'card_roles': {'103': 'line', '104': 'engine', '1079': 'engine', '1080': 'tech', '1086': 'engine', '1097': 'tech', '112': 'engine', '1122': 'engine', '1152': 'engine', '1174': 'tech', '1182': 'tech', '1219': 'engine', '122': 'engine', '1227': 'engine', '1259': 'engine', '235': 'tech', '646': 'line', '647': 'line', '648': 'win', '689': 'tech', '7': 'fuel'}, 'draw_supporters': [1080], 'engine': 'v2', 'l2': 'marnie_grimmsnarl', 'live': {'best_score': 575.2, 'last_submitted': '2026-07-11', 'submissions': 4}, 'status': 'submitted', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
