"""Deck agent: mega_lucario_tr (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1087": "tech", "1102": "engine", "1123": "tech", "1141": "tech", "1142": "engine", "1152": "engine", "1159": "tech", "1182": "tech", "1213": "engine", "1227": "engine", "6": "fuel", "673": "line", "674": "engine", "675": "engine", "676": "engine", "677": "line", "678": "win"}, "engine": "v2", "hand_reset_cards": [1087], "l2": "mega_lucario_tr", "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_lucario_tr")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1087': 'tech', '1102': 'engine', '1123': 'tech', '1141': 'tech', '1142': 'engine', '1152': 'engine', '1159': 'tech', '1182': 'tech', '1213': 'engine', '1227': 'engine', '6': 'fuel', '673': 'line', '674': 'engine', '675': 'engine', '676': 'engine', '677': 'line', '678': 'win'}, 'engine': 'v2', 'hand_reset_cards': [1087], 'l2': 'mega_lucario_tr', 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
