"""Deck agent: mega_latias (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "toolbox", "card_roles": {"1071": "engine", "1079": "engine", "1080": "engine", "1086": "engine", "1097": "engine", "1121": "engine", "1152": "engine", "1182": "tech", "1198": "engine", "1205": "engine", "1210": "engine", "1227": "engine", "1264": "tech", "140": "engine", "184": "win", "2": "fuel", "272": "tech", "326": "engine", "410": "line", "411": "line", "412": "tech", "5": "fuel", "754": "win", "756": "win", "858": "tech"}, "draw_supporters": [1080], "engine": "v2", "l2": "mega_latias", "search_items": [1210], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_latias")
PROFILE = {'archetype': 'toolbox', 'card_roles': {'1071': 'engine', '1079': 'engine', '1080': 'engine', '1086': 'engine', '1097': 'engine', '1121': 'engine', '1152': 'engine', '1182': 'tech', '1198': 'engine', '1205': 'engine', '1210': 'engine', '1227': 'engine', '1264': 'tech', '140': 'engine', '184': 'win', '2': 'fuel', '272': 'tech', '326': 'engine', '410': 'line', '411': 'line', '412': 'tech', '5': 'fuel', '754': 'win', '756': 'win', '858': 'tech'}, 'draw_supporters': [1080], 'engine': 'v2', 'l2': 'mega_latias', 'search_items': [1210], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
