"""Deck agent: mega_dragonite (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory", "archetype": "toolbox", "card_roles": {"1": "fuel", "1071": "engine", "108": "win", "1097": "tech", "1098": "tech", "1119": "tech", "1121": "engine", "1122": "engine", "1126": "engine", "1152": "engine", "1182": "tech", "1191": "tech", "1198": "engine", "1219": "engine", "1227": "engine", "124": "line", "125": "win", "1250": "tech", "126": "tech", "1264": "tech", "140": "engine", "160": "engine", "176": "win", "184": "tech", "3": "fuel", "4": "fuel", "756": "win", "902": "line", "903": "line", "904": "win"}, "energy_accel": [1098], "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [136, 1092, 1302], "discard_fuel": [], "focus": [756, 904, 108], "need": {"108": 3, "756": 3, "904": 3}, "stadiums": [1250, 1264]}, "main_attackers": [756, 176, 108, 904], "status": "candidate", "style": "evolve", "switch_cards": [1191]}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_dragonite")
PROFILE = {'_line_note': 'win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory', 'archetype': 'toolbox', 'card_roles': {'1': 'fuel', '1071': 'engine', '108': 'win', '1097': 'tech', '1098': 'tech', '1119': 'tech', '1121': 'engine', '1122': 'engine', '1126': 'engine', '1152': 'engine', '1182': 'tech', '1191': 'tech', '1198': 'engine', '1219': 'engine', '1227': 'engine', '124': 'line', '125': 'win', '1250': 'tech', '126': 'tech', '1264': 'tech', '140': 'engine', '160': 'engine', '176': 'win', '184': 'tech', '3': 'fuel', '4': 'fuel', '756': 'win', '902': 'line', '903': 'line', '904': 'win'}, 'energy_accel': [1098], 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [136, 1092, 1302], 'discard_fuel': [], 'focus': [756, 904, 108], 'need': {'108': 3, '756': 3, '904': 3}, 'stadiums': [1250, 1264]}, 'main_attackers': [756, 176, 108, 904], 'status': 'candidate', 'style': 'evolve', 'switch_cards': [1191]}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
