"""Deck agent: mega_venusaur (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1": "fuel", "1094": "engine", "1121": "engine", "1122": "engine", "1159": "tech", "1182": "tech", "1213": "engine", "1227": "engine", "1229": "tech", "1261": "engine", "650": "line", "651": "line", "652": "win", "920": "tech", "96": "engine"}, "engine": "v2", "l2": "mega_venusaur", "mega_heal_cards": [1229], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_venusaur")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1': 'fuel', '1094': 'engine', '1121': 'engine', '1122': 'engine', '1159': 'tech', '1182': 'tech', '1213': 'engine', '1227': 'engine', '1229': 'tech', '1261': 'engine', '650': 'line', '651': 'line', '652': 'win', '920': 'tech', '96': 'engine'}, 'engine': 'v2', 'l2': 'mega_venusaur', 'mega_heal_cards': [1229], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
