"""Deck agent: mega_lopunny (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1086": "engine", "1088": "engine", "1097": "engine", "1121": "engine", "1123": "engine", "1152": "engine", "1157": "engine", "1182": "tech", "1185": "engine", "1198": "tech", "1205": "engine", "1227": "engine", "140": "engine", "235": "tech", "65": "line", "66": "engine", "7": "fuel", "848": "line", "849": "win"}, "engine": "v2", "l2": "config", "line": {"big": [76, 183, 1226], "discard_fuel": [], "focus": [849, 66, 140], "need": {"140": 3, "66": 3, "849": 2}, "stadiums": []}, "main_attackers": [849], "search_items": [1185], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_lopunny")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1086': 'engine', '1088': 'engine', '1097': 'engine', '1121': 'engine', '1123': 'engine', '1152': 'engine', '1157': 'engine', '1182': 'tech', '1185': 'engine', '1198': 'tech', '1205': 'engine', '1227': 'engine', '140': 'engine', '235': 'tech', '65': 'line', '66': 'engine', '7': 'fuel', '848': 'line', '849': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [76, 183, 1226], 'discard_fuel': [], 'focus': [849, 66, 140], 'need': {'140': 3, '66': 3, '849': 2}, 'stadiums': []}, 'main_attackers': [849], 'search_items': [1185], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
