"""Deck agent: mega_diancie (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1071": "engine", "1079": "engine", "1092": "engine", "1097": "tech", "1119": "engine", "1121": "engine", "1122": "engine", "1123": "tech", "1145": "engine", "1146": "engine", "1152": "engine", "1163": "engine", "1182": "tech", "1219": "engine", "1227": "engine", "1263": "engine", "131": "line", "132": "line", "133": "engine", "184": "win", "19": "fuel", "214": "engine", "272": "tech", "5": "fuel", "766": "win", "959": "line"}, "draw_supporters": [1263], "energy_accel": [1163], "engine": "v2", "l2": "mega_diancie", "main_attackers": [766], "roles": {"766": {"payoff": true, "role": "attacker", "tier": "primary"}}, "search_items": [1092, 1145], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_diancie")
PROFILE = {'archetype': 'spread', 'card_roles': {'1071': 'engine', '1079': 'engine', '1092': 'engine', '1097': 'tech', '1119': 'engine', '1121': 'engine', '1122': 'engine', '1123': 'tech', '1145': 'engine', '1146': 'engine', '1152': 'engine', '1163': 'engine', '1182': 'tech', '1219': 'engine', '1227': 'engine', '1263': 'engine', '131': 'line', '132': 'line', '133': 'engine', '184': 'win', '19': 'fuel', '214': 'engine', '272': 'tech', '5': 'fuel', '766': 'win', '959': 'line'}, 'draw_supporters': [1263], 'energy_accel': [1163], 'engine': 'v2', 'l2': 'mega_diancie', 'main_attackers': [766], 'roles': {'766': {'payoff': True, 'role': 'attacker', 'tier': 'primary'}}, 'search_items': [1092, 1145], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
