"""Deck agent: mega_starmie (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1030": "line", "1031": "win", "1071": "engine", "1086": "engine", "1097": "engine", "112": "engine", "1121": "engine", "1152": "engine", "1174": "tech", "1182": "tech", "119": "line", "1198": "engine", "12": "fuel", "120": "line", "121": "win", "1225": "engine", "1227": "engine", "1260": "tech", "140": "tech", "17": "fuel", "2": "fuel", "235": "tech", "3": "fuel", "5": "fuel", "7": "fuel"}, "engine": "v2", "l2": "config", "line": {"big": [152, 154, 1487], "discard_fuel": [], "focus": [1031, 121, 120], "need": {"1031": 1, "120": 2, "121": 2}, "stadiums": [1260], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_starmie")
PROFILE = {'archetype': 'spread', 'card_roles': {'1030': 'line', '1031': 'win', '1071': 'engine', '1086': 'engine', '1097': 'engine', '112': 'engine', '1121': 'engine', '1152': 'engine', '1174': 'tech', '1182': 'tech', '119': 'line', '1198': 'engine', '12': 'fuel', '120': 'line', '121': 'win', '1225': 'engine', '1227': 'engine', '1260': 'tech', '140': 'tech', '17': 'fuel', '2': 'fuel', '235': 'tech', '3': 'fuel', '5': 'fuel', '7': 'fuel'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [152, 154, 1487], 'discard_fuel': [], 'focus': [1031, 121, 120], 'need': {'1031': 1, '120': 2, '121': 2}, 'stadiums': [1260], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
