"""Deck agent: mega_absol (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1086": "engine", "1092": "engine", "1097": "tech", "1116": "tech", "112": "engine", "1121": "engine", "1122": "engine", "1134": "engine", "1139": "tech", "1152": "engine", "1174": "tech", "1182": "tech", "1219": "engine", "1227": "engine", "1256": "tech", "1257": "tech", "140": "engine", "141": "engine", "230": "engine", "343": "tech", "687": "win", "7": "fuel", "833": "line", "834": "engine"}, "engine": "v2", "l2": "config", "line": {"big": [184, 994, 1203], "combo": {"finisher": 687, "finisher_attack": 994, "n": 6, "type": "exact_counters"}, "discard_fuel": [], "focus": [687, 141, 834], "need": {"141": 2, "687": 2, "834": 3}, "stadiums": [1256, 1257], "support_energy": {"112": 1}, "support_gate": "lenient"}, "search_items": [1134, 1092], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_absol")
PROFILE = {'archetype': 'spread', 'card_roles': {'1086': 'engine', '1092': 'engine', '1097': 'tech', '1116': 'tech', '112': 'engine', '1121': 'engine', '1122': 'engine', '1134': 'engine', '1139': 'tech', '1152': 'engine', '1174': 'tech', '1182': 'tech', '1219': 'engine', '1227': 'engine', '1256': 'tech', '1257': 'tech', '140': 'engine', '141': 'engine', '230': 'engine', '343': 'tech', '687': 'win', '7': 'fuel', '833': 'line', '834': 'engine'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [184, 994, 1203], 'combo': {'finisher': 687, 'finisher_attack': 994, 'n': 6, 'type': 'exact_counters'}, 'discard_fuel': [], 'focus': [687, 141, 834], 'need': {'141': 2, '687': 2, '834': 3}, 'stadiums': [1256, 1257], 'support_energy': {'112': 1}, 'support_gate': 'lenient'}, 'search_items': [1134, 1092], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
