"""Deck agent: mega_zygarde (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1051": "line", "1052": "engine", "1056": "win", "1097": "engine", "1121": "engine", "1123": "tech", "1126": "engine", "1142": "engine", "1152": "engine", "1174": "tech", "1182": "tech", "1192": "engine", "1227": "engine", "1229": "tech", "1238": "engine", "20": "fuel", "6": "fuel", "675": "engine", "676": "engine"}, "engine": "v2", "l2": "mega_zygarde", "mega_heal_cards": [1229], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_zygarde")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1051': 'line', '1052': 'engine', '1056': 'win', '1097': 'engine', '1121': 'engine', '1123': 'tech', '1126': 'engine', '1142': 'engine', '1152': 'engine', '1174': 'tech', '1182': 'tech', '1192': 'engine', '1227': 'engine', '1229': 'tech', '1238': 'engine', '20': 'fuel', '6': 'fuel', '675': 'engine', '676': 'engine'}, 'engine': 'v2', 'l2': 'mega_zygarde', 'mega_heal_cards': [1229], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
