"""Deck agent: mega_lucario (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "engine": "v2", "l2": "mega_lucario", "live": {"best_score": 699.7, "last_submitted": "2026-07-17", "submissions": 11}, "mega_heal_cards": [1229], "status": "submitted", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_lucario")
PROFILE = {'archetype': 'aggro', 'engine': 'v2', 'l2': 'mega_lucario', 'live': {'best_score': 699.7, 'last_submitted': '2026-07-17', 'submissions': 11}, 'mega_heal_cards': [1229], 'status': 'submitted', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
