"""Deck agent: mega_feraligatr (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_unused_note": "MegaFeraligatrL2 extends BeatdownPolicy, not ConfigL2, so it does NOT read the line config below; p05_deckconfig can regenerate it if this ever goes back to config", "archetype": "beatdown", "card_roles": {"10": "engine", "1071": "engine", "1079": "engine", "1086": "engine", "112": "engine", "1121": "engine", "1122": "engine", "1129": "tech", "1152": "engine", "1182": "tech", "1198": "engine", "1219": "engine", "1225": "engine", "1227": "engine", "1237": "tech", "1240": "engine", "1262": "tech", "235": "tech", "3": "fuel", "305": "line", "343": "tech", "47": "line", "48": "line", "49": "win", "66": "engine", "7": "fuel", "939": "win"}, "deck_recover_cards": [1129], "draw_supporters": [1237], "energy_accel": [1240], "engine": "v2", "l2": "mega_feraligatr", "line": {"big": [48, 76, 1347], "discard_fuel": [], "focus": [49, 939, 66], "need": {"49": 2, "66": 3, "939": 3}, "predamage": true, "stadiums": [1262], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_feraligatr")
PROFILE = {'_line_unused_note': 'MegaFeraligatrL2 extends BeatdownPolicy, not ConfigL2, so it does NOT read the line config below; p05_deckconfig can regenerate it if this ever goes back to config', 'archetype': 'beatdown', 'card_roles': {'10': 'engine', '1071': 'engine', '1079': 'engine', '1086': 'engine', '112': 'engine', '1121': 'engine', '1122': 'engine', '1129': 'tech', '1152': 'engine', '1182': 'tech', '1198': 'engine', '1219': 'engine', '1225': 'engine', '1227': 'engine', '1237': 'tech', '1240': 'engine', '1262': 'tech', '235': 'tech', '3': 'fuel', '305': 'line', '343': 'tech', '47': 'line', '48': 'line', '49': 'win', '66': 'engine', '7': 'fuel', '939': 'win'}, 'deck_recover_cards': [1129], 'draw_supporters': [1237], 'energy_accel': [1240], 'engine': 'v2', 'l2': 'mega_feraligatr', 'line': {'big': [48, 76, 1347], 'discard_fuel': [], 'focus': [49, 939, 66], 'need': {'49': 2, '66': 3, '939': 3}, 'predamage': True, 'stadiums': [1262], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
