"""Deck agent: mega_lucario_hilda (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1102": "engine", "1121": "engine", "1123": "tech", "1141": "tech", "1142": "engine", "1152": "engine", "1159": "tech", "1182": "tech", "1192": "engine", "1197": "tech", "1225": "engine", "1227": "engine", "1229": "tech", "1252": "tech", "20": "fuel", "6": "fuel", "677": "line", "678": "win"}, "engine": "v2", "l2": "mega_lucario", "live": {"best_score": 542.9, "last_submitted": "2026-07-15", "submissions": 1}, "mega_heal_cards": [1229], "status": "submitted", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_lucario_hilda")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1102': 'engine', '1121': 'engine', '1123': 'tech', '1141': 'tech', '1142': 'engine', '1152': 'engine', '1159': 'tech', '1182': 'tech', '1192': 'engine', '1197': 'tech', '1225': 'engine', '1227': 'engine', '1229': 'tech', '1252': 'tech', '20': 'fuel', '6': 'fuel', '677': 'line', '678': 'win'}, 'engine': 'v2', 'l2': 'mega_lucario', 'live': {'best_score': 542.9, 'last_submitted': '2026-07-15', 'submissions': 1}, 'mega_heal_cards': [1229], 'status': 'submitted', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
