"""Deck agent: mega_froslass (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1071": "engine", "1079": "engine", "1086": "engine", "1097": "tech", "1121": "engine", "1123": "tech", "1152": "engine", "1182": "tech", "1194": "engine", "1225": "engine", "1227": "engine", "1246": "tech", "1249": "engine", "131": "line", "132": "line", "133": "engine", "140": "engine", "17": "fuel", "184": "tech", "235": "tech", "3": "fuel", "33": "line", "34": "line", "40": "win", "860": "line", "861": "win"}, "engine": "v2", "l2": "config", "line": {"big": [33, 183, 1240], "discard_fuel": [], "focus": [40, 861, 140], "need": {"140": 3, "40": 1, "861": 1}, "stadiums": [1246, 1249]}, "main_attackers": [40], "roles": {"40": {"role": "attacker", "tier": "primary"}}, "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_froslass")
PROFILE = {'archetype': 'spread', 'card_roles': {'1071': 'engine', '1079': 'engine', '1086': 'engine', '1097': 'tech', '1121': 'engine', '1123': 'tech', '1152': 'engine', '1182': 'tech', '1194': 'engine', '1225': 'engine', '1227': 'engine', '1246': 'tech', '1249': 'engine', '131': 'line', '132': 'line', '133': 'engine', '140': 'engine', '17': 'fuel', '184': 'tech', '235': 'tech', '3': 'fuel', '33': 'line', '34': 'line', '40': 'win', '860': 'line', '861': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [33, 183, 1240], 'discard_fuel': [], 'focus': [40, 861, 140], 'need': {'140': 3, '40': 1, '861': 1}, 'stadiums': [1246, 1249]}, 'main_attackers': [40], 'roles': {'40': {'role': 'attacker', 'tier': 'primary'}}, 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
