"""Deck agent: mega_gengar (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"1071": "engine", "1079": "engine", "1080": "engine", "1086": "engine", "1097": "engine", "112": "engine", "1121": "engine", "1152": "engine", "1163": "tech", "1174": "tech", "1182": "engine", "1195": "engine", "1219": "engine", "1227": "engine", "1231": "engine", "1256": "tech", "1259": "engine", "140": "engine", "141": "engine", "235": "tech", "646": "line", "647": "line", "648": "win", "689": "tech", "7": "fuel", "770": "line", "771": "line", "772": "win"}, "draw_supporters": [1080], "energy_accel": [1163], "engine": "v2", "l2": "config", "line": {"big": [184, 937, 1117], "discard_fuel": [], "focus": [772, 648, 141], "need": {"141": 2, "648": 2, "772": 2}, "stadiums": [1259, 1256], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "search_items": [1231], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_gengar")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'1071': 'engine', '1079': 'engine', '1080': 'engine', '1086': 'engine', '1097': 'engine', '112': 'engine', '1121': 'engine', '1152': 'engine', '1163': 'tech', '1174': 'tech', '1182': 'engine', '1195': 'engine', '1219': 'engine', '1227': 'engine', '1231': 'engine', '1256': 'tech', '1259': 'engine', '140': 'engine', '141': 'engine', '235': 'tech', '646': 'line', '647': 'line', '648': 'win', '689': 'tech', '7': 'fuel', '770': 'line', '771': 'line', '772': 'win'}, 'draw_supporters': [1080], 'energy_accel': [1163], 'engine': 'v2', 'l2': 'config', 'line': {'big': [184, 937, 1117], 'discard_fuel': [], 'focus': [772, 648, 141], 'need': {'141': 2, '648': 2, '772': 2}, 'stadiums': [1259, 1256], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'search_items': [1231], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
