"""Deck agent: mega_starmie (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1030": "line", "1031": "win", "1086": "engine", "1121": "engine", "1122": "engine", "1145": "engine", "1159": "tech", "117": "tech", "1182": "tech", "1189": "engine", "1197": "tech", "1224": "engine", "1225": "engine", "1227": "engine", "1229": "engine", "1262": "tech", "3": "fuel", "414": "tech", "6": "fuel", "664": "line", "665": "line", "666": "tech", "860": "line", "861": "win"}, "draw_supporters": [1224], "engine": "v2", "l2": "config", "line": {"big": [664, 665], "discard_fuel": [], "focus": [1031, 861], "need": {"1030": 2, "1031": 2, "860": 2, "861": 2}, "stadiums": [1262], "support_energy": {"1031": 1, "861": 1}, "support_etype": {"1031": 3, "861": 3}}, "search_items": [1121, 1122, 1086, 1145, 1189], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_starmie")
PROFILE = {'archetype': 'spread', 'card_roles': {'1030': 'line', '1031': 'win', '1086': 'engine', '1121': 'engine', '1122': 'engine', '1145': 'engine', '1159': 'tech', '117': 'tech', '1182': 'tech', '1189': 'engine', '1197': 'tech', '1224': 'engine', '1225': 'engine', '1227': 'engine', '1229': 'engine', '1262': 'tech', '3': 'fuel', '414': 'tech', '6': 'fuel', '664': 'line', '665': 'line', '666': 'tech', '860': 'line', '861': 'win'}, 'draw_supporters': [1224], 'engine': 'v2', 'l2': 'config', 'line': {'big': [664, 665], 'discard_fuel': [], 'focus': [1031, 861], 'need': {'1030': 2, '1031': 2, '860': 2, '861': 2}, 'stadiums': [1262], 'support_energy': {'1031': 1, '861': 1}, 'support_etype': {'1031': 3, '861': 3}}, 'search_items': [1121, 1122, 1086, 1145, 1189], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
