"""Deck agent: mega_gardevoir (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1071": "engine", "1079": "engine", "1092": "engine", "1097": "tech", "112": "tech", "1121": "engine", "1146": "engine", "1152": "engine", "117": "tech", "1172": "tech", "1182": "tech", "1194": "engine", "1219": "engine", "1225": "engine", "1227": "engine", "1241": "tech", "1263": "engine", "140": "engine", "16": "fuel", "183": "engine", "184": "win", "19": "fuel", "272": "tech", "5": "fuel", "745": "line", "746": "line", "747": "win", "751": "engine"}, "draw_supporters": [1263], "engine": "v2", "l2": "mega_gardevoir", "search_items": [1092], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("mega_gardevoir")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1071': 'engine', '1079': 'engine', '1092': 'engine', '1097': 'tech', '112': 'tech', '1121': 'engine', '1146': 'engine', '1152': 'engine', '117': 'tech', '1172': 'tech', '1182': 'tech', '1194': 'engine', '1219': 'engine', '1225': 'engine', '1227': 'engine', '1241': 'tech', '1263': 'engine', '140': 'engine', '16': 'fuel', '183': 'engine', '184': 'win', '19': 'fuel', '272': 'tech', '5': 'fuel', '745': 'line', '746': 'line', '747': 'win', '751': 'engine'}, 'draw_supporters': [1263], 'engine': 'v2', 'l2': 'mega_gardevoir', 'search_items': [1092], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
