"""Deck agent: metagross (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "combo", "card_roles": {"1064": "tech", "1071": "engine", "1079": "engine", "1086": "engine", "1097": "tech", "1121": "engine", "1123": "tech", "1139": "engine", "1159": "tech", "1182": "tech", "1191": "tech", "1210": "engine", "1219": "engine", "1227": "engine", "1264": "tech", "184": "tech", "272": "tech", "5": "fuel", "547": "engine", "639": "line", "640": "line", "641": "win", "695": "tech", "696": "tech", "8": "fuel", "804": "line", "835": "tech"}, "engine": "v2", "l2": "metagross", "main_attackers": [641], "roles": {"641": {"payoff": true, "role": "attacker", "tier": "primary"}}, "search_items": [1210], "status": "candidate", "style": "evolve", "switch_cards": [1191]}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("metagross")
PROFILE = {'archetype': 'combo', 'card_roles': {'1064': 'tech', '1071': 'engine', '1079': 'engine', '1086': 'engine', '1097': 'tech', '1121': 'engine', '1123': 'tech', '1139': 'engine', '1159': 'tech', '1182': 'tech', '1191': 'tech', '1210': 'engine', '1219': 'engine', '1227': 'engine', '1264': 'tech', '184': 'tech', '272': 'tech', '5': 'fuel', '547': 'engine', '639': 'line', '640': 'line', '641': 'win', '695': 'tech', '696': 'tech', '8': 'fuel', '804': 'line', '835': 'tech'}, 'engine': 'v2', 'l2': 'metagross', 'main_attackers': [641], 'roles': {'641': {'payoff': True, 'role': 'attacker', 'tier': 'primary'}}, 'search_items': [1210], 'status': 'candidate', 'style': 'evolve', 'switch_cards': [1191]}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
