"""Deck agent: ns_zoroark (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "beatdown", "card_roles": {"1086": "engine", "1088": "tech", "1097": "engine", "1113": "engine", "112": "tech", "1120": "tech", "1121": "engine", "1122": "engine", "1123": "tech", "1152": "engine", "1182": "tech", "1205": "engine", "1221": "engine", "1227": "engine", "1253": "engine", "235": "tech", "292": "line", "293": "win", "303": "tech", "7": "fuel", "906": "engine"}, "energy_denial_cards": [1120], "engine": "v2", "l2": "ns_zoroark", "live": {"best_score": 454.8, "last_submitted": "2026-07-12", "submissions": 1}, "main_attackers": [293], "roles": {"293": {"role": "attacker", "tier": "primary"}}, "status": "submitted", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("ns_zoroark")
PROFILE = {'archetype': 'beatdown', 'card_roles': {'1086': 'engine', '1088': 'tech', '1097': 'engine', '1113': 'engine', '112': 'tech', '1120': 'tech', '1121': 'engine', '1122': 'engine', '1123': 'tech', '1152': 'engine', '1182': 'tech', '1205': 'engine', '1221': 'engine', '1227': 'engine', '1253': 'engine', '235': 'tech', '292': 'line', '293': 'win', '303': 'tech', '7': 'fuel', '906': 'engine'}, 'energy_denial_cards': [1120], 'engine': 'v2', 'l2': 'ns_zoroark', 'live': {'best_score': 454.8, 'last_submitted': '2026-07-12', 'submissions': 1}, 'main_attackers': [293], 'roles': {'293': {'role': 'attacker', 'tier': 'primary'}}, 'status': 'submitted', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
