"""Deck agent: ogerpon_box (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory", "archetype": "toolbox", "card_roles": {"1": "fuel", "1071": "engine", "108": "tech", "1097": "engine", "1116": "engine", "112": "engine", "1121": "engine", "1159": "tech", "1182": "tech", "1188": "engine", "1198": "engine", "1205": "engine", "1210": "engine", "1227": "engine", "1250": "engine", "140": "engine", "141": "tech", "16": "fuel", "184": "win", "2": "fuel", "209": "tech", "272": "win", "3": "fuel", "5": "fuel", "6": "fuel", "689": "tech", "7": "fuel", "756": "win", "791": "tech", "96": "engine", "979": "win"}, "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [184, 371, 1092], "discard_fuel": [], "focus": [756, 272, 141], "need": {"141": 2, "272": 2, "756": 3}, "stadiums": [1250], "support_energy": {"112": 1}, "support_etype": {"112": 7}}, "search_items": [1210, 1188], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("ogerpon_box")
PROFILE = {'_line_note': 'win-card-not-in-focus IS a real bug here, but fixing it measured FLAT at 750-1500 games -- reverted, see dead-config-audit memory', 'archetype': 'toolbox', 'card_roles': {'1': 'fuel', '1071': 'engine', '108': 'tech', '1097': 'engine', '1116': 'engine', '112': 'engine', '1121': 'engine', '1159': 'tech', '1182': 'tech', '1188': 'engine', '1198': 'engine', '1205': 'engine', '1210': 'engine', '1227': 'engine', '1250': 'engine', '140': 'engine', '141': 'tech', '16': 'fuel', '184': 'win', '2': 'fuel', '209': 'tech', '272': 'win', '3': 'fuel', '5': 'fuel', '6': 'fuel', '689': 'tech', '7': 'fuel', '756': 'win', '791': 'tech', '96': 'engine', '979': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [184, 371, 1092], 'discard_fuel': [], 'focus': [756, 272, 141], 'need': {'141': 2, '272': 2, '756': 3}, 'stadiums': [1250], 'support_energy': {'112': 1}, 'support_etype': {'112': 7}}, 'search_items': [1210, 1188], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
