"""Deck agent: okidogi_box (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1051": "line", "1052": "engine", "1097": "engine", "1142": "engine", "1152": "engine", "116": "win", "1174": "tech", "1182": "tech", "1194": "engine", "1197": "tech", "1213": "tech", "1227": "engine", "1238": "engine", "1247": "engine", "1264": "tech", "135": "win", "16": "engine", "6": "fuel", "675": "engine", "676": "engine"}, "disrupt_cards": [1197], "engine": "v2", "l2": "config", "line": {"big": [147, 175, 980], "discard_fuel": [], "focus": [135, 676, 116], "need": {"116": 2, "135": 3, "676": 1}, "stadiums": [1264, 1247]}, "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("okidogi_box")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1051': 'line', '1052': 'engine', '1097': 'engine', '1142': 'engine', '1152': 'engine', '116': 'win', '1174': 'tech', '1182': 'tech', '1194': 'engine', '1197': 'tech', '1213': 'tech', '1227': 'engine', '1238': 'engine', '1247': 'engine', '1264': 'tech', '135': 'win', '16': 'engine', '6': 'fuel', '675': 'engine', '676': 'engine'}, 'disrupt_cards': [1197], 'engine': 'v2', 'l2': 'config', 'line': {'big': [147, 175, 980], 'discard_fuel': [], 'focus': [135, 676, 116], 'need': {'116': 2, '135': 3, '676': 1}, 'stadiums': [1264, 1247]}, 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
