"""Deck agent: omatsuri (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "spread", "card_roles": {"1": "fuel", "100": "line", "1080": "engine", "1086": "engine", "1094": "engine", "1129": "tech", "1152": "engine", "1174": "tech", "1175": "tech", "1182": "tech", "1183": "engine", "1184": "tech", "1191": "tech", "1211": "tech", "1213": "tech", "1227": "engine", "1245": "engine", "1261": "tech", "18": "fuel", "240": "engine", "343": "tech", "42": "line", "73": "line", "74": "engine", "858": "tech", "89": "line", "90": "engine", "92": "line", "93": "win"}, "deck_recover_cards": [1129], "engine": "v2", "l2": "omatsuri", "residual_cards": [1080, 1183, 1191, 1211], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("omatsuri")
PROFILE = {'archetype': 'spread', 'card_roles': {'1': 'fuel', '100': 'line', '1080': 'engine', '1086': 'engine', '1094': 'engine', '1129': 'tech', '1152': 'engine', '1174': 'tech', '1175': 'tech', '1182': 'tech', '1183': 'engine', '1184': 'tech', '1191': 'tech', '1211': 'tech', '1213': 'tech', '1227': 'engine', '1245': 'engine', '1261': 'tech', '18': 'fuel', '240': 'engine', '343': 'tech', '42': 'line', '73': 'line', '74': 'engine', '858': 'tech', '89': 'line', '90': 'engine', '92': 'line', '93': 'win'}, 'deck_recover_cards': [1129], 'engine': 'v2', 'l2': 'omatsuri', 'residual_cards': [1080, 1183, 1191, 1211], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
