"""Deck agent: raging_bolt (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "toolbox", "card_roles": {"1": "fuel", "1071": "engine", "108": "tech", "1080": "engine", "1097": "engine", "1098": "engine", "1116": "engine", "1121": "engine", "1182": "tech", "1188": "engine", "1198": "engine", "1205": "engine", "1227": "engine", "1250": "engine", "140": "engine", "184": "engine", "209": "tech", "272": "win", "3": "fuel", "4": "fuel", "5": "fuel", "6": "fuel", "63": "win", "75": "tech", "756": "win", "96": "engine", "978": "tech"}, "draw_supporters": [1080], "energy_accel": [1098], "engine": "v2", "l2": "config", "line": {"bench_target": 8, "big": [72, 371, 1092], "discard_fuel": [], "focus": [756, 272, 63], "need": {"272": 2, "63": 2, "756": 3}, "stadiums": [1250]}, "search_items": [1188], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("raging_bolt")
PROFILE = {'archetype': 'toolbox', 'card_roles': {'1': 'fuel', '1071': 'engine', '108': 'tech', '1080': 'engine', '1097': 'engine', '1098': 'engine', '1116': 'engine', '1121': 'engine', '1182': 'tech', '1188': 'engine', '1198': 'engine', '1205': 'engine', '1227': 'engine', '1250': 'engine', '140': 'engine', '184': 'engine', '209': 'tech', '272': 'win', '3': 'fuel', '4': 'fuel', '5': 'fuel', '6': 'fuel', '63': 'win', '75': 'tech', '756': 'win', '96': 'engine', '978': 'tech'}, 'draw_supporters': [1080], 'energy_accel': [1098], 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 8, 'big': [72, 371, 1092], 'discard_fuel': [], 'focus': [756, 272, 63], 'need': {'272': 2, '63': 2, '756': 3}, 'stadiums': [1250]}, 'search_items': [1188], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
