"""Deck agent: rockets_honchkrow (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_note": "keyword buckets keyed by cardId -- 'Team Rocket's X' names carry no function keyword, so Transceiver/Proton/Giovanni/Archer were offered thousands of times and played 0 (tools/deck_bottleneck.py, 2026-07-21)", "archetype": "aggro", "bench_target": 4, "card_roles": {"1077": "engine", "1097": "engine", "1109": "engine", "1121": "engine", "1134": "engine", "1152": "engine", "1216": "engine", "1217": "engine", "1218": "engine", "1219": "engine", "1220": "engine", "1257": "engine", "15": "fuel", "17": "fuel", "414": "tech", "463": "line", "473": "line", "474": "win", "891": "win"}, "draw_supporters": [1216, 1217, 1219, 1220], "draw_threshold": 5, "engine": "v2", "gust_cards": [1218], "l2": "config", "line": {"bench_target": 4, "big": [891], "discard_fuel": [], "focus": [891, 463, 474, 473], "need": {"463": 4, "473": 2, "474": 2, "891": 3}, "stadiums": [1257]}, "main_attackers": [891, 474], "search_items": [1134, 1077], "status": "candidate", "style": "evolve", "switch_cards": [1218]}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("rockets_honchkrow")
PROFILE = {'_note': "keyword buckets keyed by cardId -- 'Team Rocket's X' names carry no function keyword, so Transceiver/Proton/Giovanni/Archer were offered thousands of times and played 0 (tools/deck_bottleneck.py, 2026-07-21)", 'archetype': 'aggro', 'bench_target': 4, 'card_roles': {'1077': 'engine', '1097': 'engine', '1109': 'engine', '1121': 'engine', '1134': 'engine', '1152': 'engine', '1216': 'engine', '1217': 'engine', '1218': 'engine', '1219': 'engine', '1220': 'engine', '1257': 'engine', '15': 'fuel', '17': 'fuel', '414': 'tech', '463': 'line', '473': 'line', '474': 'win', '891': 'win'}, 'draw_supporters': [1216, 1217, 1219, 1220], 'draw_threshold': 5, 'engine': 'v2', 'gust_cards': [1218], 'l2': 'config', 'line': {'bench_target': 4, 'big': [891], 'discard_fuel': [], 'focus': [891, 463, 474, 473], 'need': {'463': 4, '473': 2, '474': 2, '891': 3}, 'stadiums': [1257]}, 'main_attackers': [891, 474], 'search_items': [1134, 1077], 'status': 'candidate', 'style': 'evolve', 'switch_cards': [1218]}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
