"""Deck agent: rockets_spidops (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_note": "scouted from leaderboard #3 THIRD PTCG Club 1191.9 (2026-07-19); buckets keyed by cardId (names don't match)", "archetype": "combo", "bench_target": 5, "card_roles": {"1": "fuel", "1094": "engine", "1097": "engine", "1119": "engine", "1134": "engine", "1152": "engine", "1159": "tech", "1175": "tech", "1216": "engine", "1217": "tech", "1218": "engine", "1219": "engine", "1220": "engine", "1227": "engine", "1257": "tech", "15": "engine", "400": "engine", "401": "engine", "414": "line", "431": "win", "432": "line", "463": "engine", "5": "fuel"}, "draw_supporters": [1216, 1220, 1219, 1217], "draw_threshold": 4, "engine": "v2", "l2": "config", "line": {"bench_target": 5, "big": [608, 560], "discard_fuel": [], "focus": [431, 401, 414], "need": {"401": 2, "414": 3, "431": 3}, "stadiums": [1257]}, "main_attackers": [431, 401], "search_items": [1134], "status": "candidate", "style": "aggro", "switch_cards": [1218]}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("rockets_spidops")
PROFILE = {'_note': "scouted from leaderboard #3 THIRD PTCG Club 1191.9 (2026-07-19); buckets keyed by cardId (names don't match)", 'archetype': 'combo', 'bench_target': 5, 'card_roles': {'1': 'fuel', '1094': 'engine', '1097': 'engine', '1119': 'engine', '1134': 'engine', '1152': 'engine', '1159': 'tech', '1175': 'tech', '1216': 'engine', '1217': 'tech', '1218': 'engine', '1219': 'engine', '1220': 'engine', '1227': 'engine', '1257': 'tech', '15': 'engine', '400': 'engine', '401': 'engine', '414': 'line', '431': 'win', '432': 'line', '463': 'engine', '5': 'fuel'}, 'draw_supporters': [1216, 1220, 1219, 1217], 'draw_threshold': 4, 'engine': 'v2', 'l2': 'config', 'line': {'bench_target': 5, 'big': [608, 560], 'discard_fuel': [], 'focus': [431, 401, 414], 'need': {'401': 2, '414': 3, '431': 3}, 'stadiums': [1257]}, 'main_attackers': [431, 401], 'search_items': [1134], 'status': 'candidate', 'style': 'aggro', 'switch_cards': [1218]}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
