"""Deck agent: rockets_mewtwo (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_note": "keyword buckets keyed by cardId -- 'Team Rocket's X' names carry no function keyword, so Transceiver/Proton/Giovanni/Archer were offered thousands of times and played 0 (tools/deck_bottleneck.py, 2026-07-21)", "archetype": "combo", "card_roles": {"1": "fuel", "1094": "engine", "1097": "engine", "1116": "tech", "1121": "engine", "1134": "engine", "1158": "tech", "1175": "tech", "1216": "engine", "1217": "engine", "1218": "tech", "1219": "engine", "1220": "engine", "1227": "engine", "1257": "engine", "15": "engine", "272": "tech", "400": "line", "401": "engine", "414": "engine", "431": "win", "434": "tech", "464": "tech"}, "draw_supporters": [1216, 1217, 1219, 1220], "engine": "v2", "gust_cards": [1218], "l2": "rockets_mewtwo", "main_attackers": [431], "search_items": [1134], "status": "candidate", "style": "aggro", "switch_cards": [1218]}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("rockets_mewtwo")
PROFILE = {'_note': "keyword buckets keyed by cardId -- 'Team Rocket's X' names carry no function keyword, so Transceiver/Proton/Giovanni/Archer were offered thousands of times and played 0 (tools/deck_bottleneck.py, 2026-07-21)", 'archetype': 'combo', 'card_roles': {'1': 'fuel', '1094': 'engine', '1097': 'engine', '1116': 'tech', '1121': 'engine', '1134': 'engine', '1158': 'tech', '1175': 'tech', '1216': 'engine', '1217': 'engine', '1218': 'tech', '1219': 'engine', '1220': 'engine', '1227': 'engine', '1257': 'engine', '15': 'engine', '272': 'tech', '400': 'line', '401': 'engine', '414': 'engine', '431': 'win', '434': 'tech', '464': 'tech'}, 'draw_supporters': [1216, 1217, 1219, 1220], 'engine': 'v2', 'gust_cards': [1218], 'l2': 'rockets_mewtwo', 'main_attackers': [431], 'search_items': [1134], 'status': 'candidate', 'style': 'aggro', 'switch_cards': [1218]}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
