"""Deck agent: slowking (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "DECK FIXED to the live top-20 composition (user decision 2026-08-09): Smoochum x2 / Conkeldurr(115) / Annihilape(224) / Ciphermaniac's(1188) x4. The pilot is held at slowking_hybrid until a replacement BEATS it -- SlowkingLiveL2 measured -14.6pt on all three decklists and its cause was never found, so it must not ship enabled.", "archetype": "combo", "card_roles": {"1071": "engine", "1092": "engine", "1097": "engine", "1121": "engine", "1123": "tech", "1146": "engine", "1152": "engine", "1156": "tech", "1175": "tech", "1227": "engine", "1248": "engine", "140": "engine", "144": "engine", "162": "line", "163": "win", "184": "win", "19": "fuel", "272": "win", "276": "engine", "377": "engine", "5": "fuel", "756": "win", "9": "fuel"}, "engine": "v2", "l2": "slowking_hybrid", "line": {"big": [146, 618, 188], "discard_fuel": [5], "focus": [163, 183], "need": {"163": 2, "183": 1}, "stadiums": [1248]}, "main_attackers": [163], "residual_cards": [1092], "seek_payloads": [115, 224, 183, 144], "status": "piloted from the #1/#2 ladder agents' own replays: Kangaskhan walls and draws, Smoochum attacks for free energy, Slowking always Seeks", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("slowking")
PROFILE = {'_line_note': "DECK FIXED to the live top-20 composition (user decision 2026-08-09): Smoochum x2 / Conkeldurr(115) / Annihilape(224) / Ciphermaniac's(1188) x4. The pilot is held at slowking_hybrid until a replacement BEATS it -- SlowkingLiveL2 measured -14.6pt on all three decklists and its cause was never found, so it must not ship enabled.", 'archetype': 'combo', 'card_roles': {'1071': 'engine', '1092': 'engine', '1097': 'engine', '1121': 'engine', '1123': 'tech', '1146': 'engine', '1152': 'engine', '1156': 'tech', '1175': 'tech', '1227': 'engine', '1248': 'engine', '140': 'engine', '144': 'engine', '162': 'line', '163': 'win', '184': 'win', '19': 'fuel', '272': 'win', '276': 'engine', '377': 'engine', '5': 'fuel', '756': 'win', '9': 'fuel'}, 'engine': 'v2', 'l2': 'slowking_hybrid', 'line': {'big': [146, 618, 188], 'discard_fuel': [5], 'focus': [163, 183], 'need': {'163': 2, '183': 1}, 'stadiums': [1248]}, 'main_attackers': [163], 'residual_cards': [1092], 'seek_payloads': [115, 224, 183, 144], 'status': "piloted from the #1/#2 ladder agents' own replays: Kangaskhan walls and draws, Smoochum attacks for free energy, Slowking always Seeks", 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
