"""Deck agent: slowking (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"_line_note": "Kyurem(144)/Metagross(276)/Zeraora(377) are AMMO for Slowking's Seek Inspiration (fires their attacks for {P}{C}); Metagross intentionally has no Metang/Rare Candy. Do NOT remove them as 'unplayable'. Energy 11->15 (+5.6pt) came from Ciphermaniac's x4, which is measured dead and whose stacking thesis was refuted.", "archetype": "combo", "card_roles": {"1071": "engine", "1092": "engine", "1097": "engine", "1121": "engine", "1123": "tech", "1146": "engine", "1152": "engine", "1156": "tech", "1175": "tech", "1227": "engine", "1248": "engine", "140": "engine", "144": "engine", "162": "line", "163": "win", "184": "win", "19": "fuel", "272": "win", "276": "engine", "377": "engine", "5": "fuel", "756": "win", "9": "fuel"}, "engine": "v2", "l2": "slowking_hybrid", "line": {"big": [243, 371, 1092], "discard_fuel": [5], "focus": [756, 272, 184, 163], "need": {"163": 2, "184": 3, "272": 2, "756": 3}, "stadiums": [1248]}, "main_attackers": [756, 163], "residual_cards": [1092], "seek_payloads": [144, 276, 377], "status": "hybrid: Mega Kangaskhan clock + Seek Inspiration secondary (modern competitive shape)", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("slowking")
PROFILE = {'_line_note': "Kyurem(144)/Metagross(276)/Zeraora(377) are AMMO for Slowking's Seek Inspiration (fires their attacks for {P}{C}); Metagross intentionally has no Metang/Rare Candy. Do NOT remove them as 'unplayable'. Energy 11->15 (+5.6pt) came from Ciphermaniac's x4, which is measured dead and whose stacking thesis was refuted.", 'archetype': 'combo', 'card_roles': {'1071': 'engine', '1092': 'engine', '1097': 'engine', '1121': 'engine', '1123': 'tech', '1146': 'engine', '1152': 'engine', '1156': 'tech', '1175': 'tech', '1227': 'engine', '1248': 'engine', '140': 'engine', '144': 'engine', '162': 'line', '163': 'win', '184': 'win', '19': 'fuel', '272': 'win', '276': 'engine', '377': 'engine', '5': 'fuel', '756': 'win', '9': 'fuel'}, 'engine': 'v2', 'l2': 'slowking_hybrid', 'line': {'big': [243, 371, 1092], 'discard_fuel': [5], 'focus': [756, 272, 184, 163], 'need': {'163': 2, '184': 3, '272': 2, '756': 3}, 'stadiums': [1248]}, 'main_attackers': [756, 163], 'residual_cards': [1092], 'seek_payloads': [144, 276, 377], 'status': 'hybrid: Mega Kangaskhan clock + Seek Inspiration secondary (modern competitive shape)', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
