"""Deck agent: staryu (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1030": "line", "1031": "win", "1079": "engine", "1086": "engine", "1097": "engine", "1120": "tech", "1121": "engine", "1122": "engine", "1145": "engine", "1159": "tech", "1189": "engine", "1223": "tech", "1225": "engine", "1227": "engine", "1229": "tech", "17": "engine", "3": "fuel", "664": "line", "665": "line", "666": "engine"}, "draw_supporters": [1223], "energy_denial_cards": [1120], "engine": "v2", "l2": "config", "line": {"big": [964, 965, 1487], "discard_fuel": [], "focus": [1031, 666, 665], "need": {"1031": 1, "665": 1, "666": 1}, "stadiums": []}, "search_items": [1145, 1189], "status": "candidate", "style": "evolve"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("staryu")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1030': 'line', '1031': 'win', '1079': 'engine', '1086': 'engine', '1097': 'engine', '1120': 'tech', '1121': 'engine', '1122': 'engine', '1145': 'engine', '1159': 'tech', '1189': 'engine', '1223': 'tech', '1225': 'engine', '1227': 'engine', '1229': 'tech', '17': 'engine', '3': 'fuel', '664': 'line', '665': 'line', '666': 'engine'}, 'draw_supporters': [1223], 'energy_denial_cards': [1120], 'engine': 'v2', 'l2': 'config', 'line': {'big': [964, 965, 1487], 'discard_fuel': [], 'focus': [1031, 666, 665], 'need': {'1031': 1, '665': 1, '666': 1}, 'stadiums': []}, 'search_items': [1145, 1189], 'status': 'candidate', 'style': 'evolve'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
