"""Deck agent: trevenant_control (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1086": "engine", "1088": "engine", "1097": "tech", "1115": "engine", "1121": "engine", "1152": "engine", "1171": "engine", "1182": "engine", "1227": "engine", "1255": "tech", "140": "engine", "304": "engine", "309": "line", "310": "engine", "5": "fuel", "7": "fuel", "878": "line", "879": "win"}, "engine": "v2", "l2": "config", "line": {"big": [1268, 183], "discard_fuel": [], "focus": [879, 140], "need": {"140": 3, "879": 3}, "stadiums": [1255]}, "main_attackers": [879], "search_items": [1115], "status": "candidate", "style": "spread"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("trevenant_control")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1086': 'engine', '1088': 'engine', '1097': 'tech', '1115': 'engine', '1121': 'engine', '1152': 'engine', '1171': 'engine', '1182': 'engine', '1227': 'engine', '1255': 'tech', '140': 'engine', '304': 'engine', '309': 'line', '310': 'engine', '5': 'fuel', '7': 'fuel', '878': 'line', '879': 'win'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [1268, 183], 'discard_fuel': [], 'focus': [879, 140], 'need': {'140': 3, '879': 3}, 'stadiums': [1255]}, 'main_attackers': [879], 'search_items': [1115], 'status': 'candidate', 'style': 'spread'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
