"""Deck agent: volcanion_box (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "ramp", "card_roles": {"1071": "engine", "1088": "tech", "1097": "tech", "1118": "engine", "1121": "engine", "1122": "engine", "1152": "tech", "1182": "tech", "1198": "engine", "1205": "engine", "1227": "engine", "1256": "tech", "140": "engine", "2": "fuel", "259": "win", "573": "win", "663": "tech", "855": "tech"}, "engine": "v2", "l2": "config", "line": {"big": [357, 819, 962], "discard_fuel": [], "focus": [573, 259, 663], "need": {"259": 3, "573": 3, "663": 3}, "stadiums": [1256]}, "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("volcanion_box")
PROFILE = {'archetype': 'ramp', 'card_roles': {'1071': 'engine', '1088': 'tech', '1097': 'tech', '1118': 'engine', '1121': 'engine', '1122': 'engine', '1152': 'tech', '1182': 'tech', '1198': 'engine', '1205': 'engine', '1227': 'engine', '1256': 'tech', '140': 'engine', '2': 'fuel', '259': 'win', '573': 'win', '663': 'tech', '855': 'tech'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [357, 819, 962], 'discard_fuel': [], 'focus': [573, 259, 663], 'need': {'259': 3, '573': 3, '663': 3}, 'stadiums': [1256]}, 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
