"""Deck agent: zangoose (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {"archetype": "aggro", "card_roles": {"1002": "win", "1086": "engine", "1097": "engine", "1119": "tech", "1121": "engine", "1122": "engine", "1125": "engine", "1152": "tech", "1182": "tech", "1205": "engine", "1210": "engine", "1227": "engine", "1231": "tech", "140": "engine", "3": "fuel", "305": "engine"}, "engine": "v2", "l2": "config", "line": {"big": [183, 424, 1446], "discard_fuel": [], "focus": [1002, 140, 305], "need": {"1002": 3, "140": 3, "305": 2}, "stadiums": []}, "search_items": [1210, 1231], "status": "candidate", "style": "aggro"}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("zangoose")
PROFILE = {'archetype': 'aggro', 'card_roles': {'1002': 'win', '1086': 'engine', '1097': 'engine', '1119': 'tech', '1121': 'engine', '1122': 'engine', '1125': 'engine', '1152': 'tech', '1182': 'tech', '1205': 'engine', '1210': 'engine', '1227': 'engine', '1231': 'tech', '140': 'engine', '3': 'fuel', '305': 'engine'}, 'engine': 'v2', 'l2': 'config', 'line': {'big': [183, 424, 1446], 'discard_fuel': [], 'focus': [1002, 140, 305], 'need': {'1002': 3, '140': 3, '305': 2}, 'stadiums': []}, 'search_items': [1210, 1231], 'status': 'candidate', 'style': 'aggro'}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
