"""Regenerate agents/<deck>.py from agents/tuning.json.

Each deck has one agent (agent name == deck name). Per-deck tuning (style +
optional main_attackers/accel/play hints) lives in agents/tuning.json; this
script bakes it into self-contained agent files so submissions stay
main.py + deck.csv + cg/ (no runtime dependency on tuning.json).

This is the "apply tuning" step of the improvement loop:
    edit agents/tuning.json  ->  python tools/generate_agents.py  ->  re-evaluate

Usage:
    python tools/generate_agents.py           # regenerate all
    python tools/generate_agents.py a b c      # only decks a, b, c
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS = os.path.join(ROOT, "agents")
DECKS = os.path.join(ROOT, "decks")
TUNING = os.path.join(AGENTS, "tuning.json")

# engine_v2 decks MUST be generated as the same wrapper tools/build_engine_v2_submission.py
# bundles (DECK = load_deck(name); PROFILE = <whole tuning entry>; make_policy once at
# import; agent() -> _POLICY.act). Otherwise load_agent()/tools/evaluate.py silently test
# _engine+policies.py while the submitted bundle runs engine_v2 -- the two disagree hard
# (on mega_lucario: first attack turn 5.1 legacy vs 8.2 v2), so every "measurement" of an
# engine_v2 change was measuring code that never ships.
V2_TEMPLATE = '''"""Deck agent: {name} (auto-generated by tools/generate_agents.py).

DO NOT EDIT BY HAND. Edit agents/tuning.json and rerun tools/generate_agents.py.
Engine: engine_v2 -- tuning.json says engine="v2". This is the SAME wrapper
tools/build_engine_v2_submission.py bundles, so what you test here is what ships.
Profile for this deck: {tuning_repr}
"""
from agents.engine_v2 import load_deck, make_policy

DECK = load_deck("{name}")
PROFILE = {profile_repr}
_POLICY = make_policy(DECK, PROFILE)


def agent(obs_dict: dict) -> list[int]:
    return _POLICY.act(obs_dict)
'''


def _hints_literal(entry):
    """Build the HINTS python literal (or None) from a tuning.json entry."""
    parts = {}
    if entry.get("main_attackers"):
        ids = ", ".join(str(i) for i in entry["main_attackers"])
        parts["main_attackers"] = "{" + ids + "}"
    for key in ("accel", "play"):
        if entry.get(key):
            parts[key] = "(" + ", ".join(repr(s) for s in entry[key]) + ",)"
    # boolean hints (opt-in engine behaviours that are not universally right)
    for key in ("promote_ready",):
        if entry.get(key):
            parts[key] = "True"
    # per-deck card importance: {card_id: tier}
    if entry.get("card_roles"):
        body = ", ".join(f"{int(k)}: {v!r}" for k, v in sorted(entry["card_roles"].items(), key=lambda x: int(x[0])))
        parts["card_roles"] = "{" + body + "}"
    if not parts:
        return "None"
    return "{" + ", ".join(f'"{k}": {v}' for k, v in parts.items()) + "}"


def main(only=None):
    tuning = json.load(open(TUNING, encoding="utf-8"))
    decks = sorted(f[:-4] for f in os.listdir(DECKS) if f.endswith(".csv"))
    written = 0
    v2 = 0
    for name in decks:
        if only and name not in only:
            continue
        entry = tuning.get(name, {"style": "aggro"})
        engine = entry.get("engine") or ("v2" if entry.get("l2") else "legacy")
        if engine == "v2":
            v2 += 1
            src = V2_TEMPLATE.format(
                name=name, profile_repr=repr(entry),
                tuning_repr=json.dumps(entry, ensure_ascii=False),
            )
        else:
            # agents/policies.py was deleted once all 60 decks moved to engine_v2 (see
            # engine="v2" in tuning.json). There is no legacy template any more, and a
            # silently-wrong engine is exactly what this refactor existed to stop.
            raise SystemExit(
                f"{name}: tuning.json says engine={engine!r}, but the legacy engine "
                f"(agents/policies.py) no longer exists. Every deck must ship engine_v2 "
                f"(set engine=\"v2\" and an l2/archetype).")
        with open(os.path.join(AGENTS, name + ".py"), "w") as f:
            f.write(src)
        written += 1
    # warn about tuning entries with no matching deck
    orphan = [n for n in tuning if n not in decks]
    print(f"generated {written} agent(s) ({v2} engine_v2, {written - v2} legacy)"
          + (f"; tuning.json has {len(orphan)} orphan entries: {orphan}" if orphan else ""))


if __name__ == "__main__":
    main(only=set(sys.argv[1:]) or None)
